// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"fmt"
	"github.com/gorundebug/servicelib/runtime"
	log "github.com/gorundebug/servicelib/runtime/environment/log"
	"sync"

	inventoryserviceapi "github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi"
	config "github.com/gorundebug/orderservice/internal/config"
	"golang.org/x/sync/errgroup"
	"google.golang.org/grpc"
)

type serviceClients struct {
	inventoryServiceApiGrpcClientConn *grpc.ClientConn
	inventoryServiceApiGrpcClient     inventoryserviceapi.InventoryServiceApiClient
}

func (clients *serviceClients) initClients(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment, makers *serviceMakers) error {

	if err := clients.initGRPC(ctx, cfg, env, makers); err != nil {
		return err
	}
	return nil
}
func (clients *serviceClients) initGRPC(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment, makers *serviceMakers) error {
	eg, egCtx := errgroup.WithContext(ctx)
	eg.Go(func() error {
		conn, client, err := makers.inventoryServiceApiGrpcClientMaker(egCtx, &cfg.DataConnectors.InventoryServiceApi, env)
		if err != nil {
			return fmt.Errorf("init gRPC client for 'Inventory Service API' failed: %w", err)
		}
		clients.inventoryServiceApiGrpcClientConn = conn
		clients.inventoryServiceApiGrpcClient = client
		return nil
	})
	return eg.Wait()
}

func (clients *serviceClients) close(timeoutCtx context.Context, s *Service) {
	// Outbound clients and user-owned resources are last: accepted handlers
	// and graph shutdown callbacks may still need them in earlier phases.
	cleanupWg := sync.WaitGroup{}

	cleanupWg.Add(1)
	go func() {
		defer cleanupWg.Done()
		if err := clients.inventoryServiceApiGrpcClientConn.Close(); err != nil {
			s.Log().Warn(timeoutCtx, "gRPC client close error", log.Str("server", "Inventory Service API"), log.Err(err))
		}
	}()

	cleanupWg.Add(1)
	go func() {
		defer cleanupWg.Done()
		s.stop(timeoutCtx)
	}()
	cleanupDone := make(chan struct{})
	go func() {
		cleanupWg.Wait()
		close(cleanupDone)
	}()
	select {
	case <-cleanupDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "service cleanup timed out", log.Err(timeoutCtx.Err()))
	}
}
