// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"github.com/gorundebug/servicelib/runtime"

	config "github.com/gorundebug/orderservice/internal/config"
)

// Connector resources are owned and registered by the runtime environment.
// Do not keep a duplicate registry in the generated service.
func initConnectors(cfg *config.Config, env runtime.RuntimeEnvironment) error {

	return nil
}
