// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"github.com/gorundebug/servicelib/runtime"

	processorderitem "github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi/processorderitem"
	types2 "github.com/gorundebug/model_go/pkg/types"
	endpoint "github.com/gorundebug/orderservice/internal/functions/endpoint"
	types "github.com/gorundebug/orderservice/internal/types"
)

type serviceHandlers struct {
	processOrder endpoint.ProcessOrderSourceType
}

type serviceEndpoints struct {
	handlers serviceHandlers

	processOrder runtime.Consumer[*types.Order]

	processOrderItemProcessOrderItem    runtime.Consumer[*types2.OrderItem]
	publishOrderProcessedOrderProcessed runtime.Consumer[*types2.OrderProcessed]
}

func (endpoints *serviceEndpoints) initEndpoints(s *Service) error {
	var err error

	if endpoints.processOrder, endpoints.handlers.processOrder, err = endpoint.MakeEndpointConsumerProcessOrderSource(s.streams.processOrder, s.functions.endpointProcessOrderSource); err != nil {
		return err
	}

	if endpoints.processOrderItemProcessOrderItem, err = endpoint.MakeEndpointConsumerProcessOrderItemSink(s.streams.processOrderItem, s.functions.endpointProcessOrderItemSink, func(ctx context.Context, req *processorderitem.ProcessOrderItemRequest) (*processorderitem.ProcessOrderItemResponse, error) {
		return s.clients.inventoryServiceApiGrpcClient.ProcessOrderItem(ctx, req)
	}); err != nil {
		return err
	}
	if endpoints.publishOrderProcessedOrderProcessed, err = endpoint.MakeEndpointConsumerOrderProcessedEndpointSink(s.streams.publishOrderProcessed, s.functions.endpointOrderProcessedEndpointSink); err != nil {
		return err
	}
	return err
}
