// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"github.com/gorundebug/servicelib/runtime"
	"golang.org/x/sync/errgroup"

	endpoint "github.com/gorundebug/orderservice/internal/functions/endpoint"
	order "github.com/gorundebug/orderservice/internal/functions/order"
)

type serviceFunctions struct {
	orderProcessOrderItems              *order.ProcessOrderItems
	orderMapOrderItemResultToOrderState *order.MapOrderItemResultToOrderState
	orderSoftDeadline                   *order.SoftDeadline
	orderMapToOrderState                *order.MapToOrderState
	orderMapToOrderProcessed            *order.MapToOrderProcessed

	endpointProcessOrderSource *endpoint.ProcessOrderSource

	endpointProcessOrderItemSink       *endpoint.ProcessOrderItemSink
	endpointOrderProcessedEndpointSink *endpoint.OrderProcessedEndpointSink
}

type makerTaskGroup interface{ Go(func() error) }

func (functions *serviceFunctions) initFunctions(ctx context.Context, env runtime.RuntimeEnvironment, makers *serviceMakers) error {

	eg, egCtx := errgroup.WithContext(ctx)
	functions.scheduleFunctions(eg, egCtx, env, makers)
	if err := eg.Wait(); err != nil {
		return err
	}

	return nil
}

func (functions *serviceFunctions) scheduleFunctions(tasks makerTaskGroup, ctx context.Context, env runtime.RuntimeEnvironment, makers *serviceMakers) {

	eg := tasks
	egCtx := ctx

	if makers.orderProcessOrderItemsMaker != nil {
		eg.Go(func() error {
			var err error
			functions.orderProcessOrderItems, err = makers.orderProcessOrderItemsMaker(egCtx, env)
			return err
		})
	}
	if makers.orderMapOrderItemResultToOrderStateMaker != nil {
		eg.Go(func() error {
			var err error
			functions.orderMapOrderItemResultToOrderState, err = makers.orderMapOrderItemResultToOrderStateMaker(egCtx, env)
			return err
		})
	}
	if makers.orderSoftDeadlineMaker != nil {
		eg.Go(func() error {
			var err error
			functions.orderSoftDeadline, err = makers.orderSoftDeadlineMaker(egCtx, env)
			return err
		})
	}
	if makers.orderMapToOrderStateMaker != nil {
		eg.Go(func() error {
			var err error
			functions.orderMapToOrderState, err = makers.orderMapToOrderStateMaker(egCtx, env)
			return err
		})
	}
	if makers.orderMapToOrderProcessedMaker != nil {
		eg.Go(func() error {
			var err error
			functions.orderMapToOrderProcessed, err = makers.orderMapToOrderProcessedMaker(egCtx, env)
			return err
		})
	}

	if makers.endpointProcessOrderSourceMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointProcessOrderSource, err = makers.endpointProcessOrderSourceMaker(egCtx, env)
			return err
		})
	}

	if makers.endpointProcessOrderItemSinkMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointProcessOrderItemSink, err = makers.endpointProcessOrderItemSinkMaker(egCtx, env)
			return err
		})
	}
	if makers.endpointOrderProcessedEndpointSinkMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointOrderProcessedEndpointSink, err = makers.endpointOrderProcessedEndpointSinkMaker(egCtx, env)
			return err
		})
	}
}
