// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"net/http"

	"github.com/gorundebug/order_service_api/pkg/generated/openapi/orderserviceapi"
)

var _ orderserviceapi.ServerInterface = (*HttpService)(nil)

type HttpService struct {
	service *Service
}

func (s *HttpService) Processorder(w http.ResponseWriter, r *http.Request) {
	s.service.endpoints.handlers.processOrder(w, r)
}
