// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"fmt"
	inventoryserviceapi "github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi"
	endpoint "github.com/gorundebug/orderservice/internal/functions/endpoint"
	order "github.com/gorundebug/orderservice/internal/functions/order"
	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	"google.golang.org/grpc"
	"google.golang.org/grpc/attributes"
	_ "google.golang.org/grpc/balancer/roundrobin"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/resolver"
	"google.golang.org/grpc/resolver/manual"
	"google.golang.org/grpc/stats"
	"net/http"
	"strings"
)

type serviceMakers struct {
	httpServerMaker                    func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMuxMaker                       func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)
	inventoryServiceApiGrpcClientMaker func(context.Context, *runtimecfg.GrpcDataConnectorConfig, runtime.RuntimeEnvironment) (*grpc.ClientConn, inventoryserviceapi.InventoryServiceApiClient, error)

	orderProcessOrderItemsMaker              func(ctx context.Context, env environment.ServiceEnvironment) (*order.ProcessOrderItems, error)
	orderMapOrderItemResultToOrderStateMaker func(ctx context.Context, env environment.ServiceEnvironment) (*order.MapOrderItemResultToOrderState, error)
	orderSoftDeadlineMaker                   func(ctx context.Context, env environment.ServiceEnvironment) (*order.SoftDeadline, error)
	orderMapToOrderStateMaker                func(ctx context.Context, env environment.ServiceEnvironment) (*order.MapToOrderState, error)
	orderMapToOrderProcessedMaker            func(ctx context.Context, env environment.ServiceEnvironment) (*order.MapToOrderProcessed, error)

	endpointProcessOrderSourceMaker func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.ProcessOrderSource, error)

	endpointProcessOrderItemSinkMaker       func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSink, error)
	endpointOrderProcessedEndpointSinkMaker func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSink, error)
}

func (makers *serviceMakers) initMakers(ctx context.Context) error {
	makers.httpMuxMaker = func(_ context.Context, _ runtime.RuntimeEnvironment) (*http.ServeMux, error) {
		return http.NewServeMux(), nil
	}
	if makers.inventoryServiceApiGrpcClientMaker == nil {
		makers.inventoryServiceApiGrpcClientMaker = func(ctx context.Context, cfg *runtimecfg.GrpcDataConnectorConfig, env runtime.RuntimeEnvironment) (*grpc.ClientConn, inventoryserviceapi.InventoryServiceApiClient, error) {
			connectionsCount := cfg.ConnectionsCount
			if connectionsCount == 0 {
				connectionsCount = 1
			}
			if connectionsCount < 1 {
				return nil, nil, fmt.Errorf("gRPC connector %q connectionsCount must be at least 1", cfg.Name)
			}
			opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}
			var statsHandlers []stats.Handler
			if me := env.MetricsEngine(); me != nil {
				if h := me.GRPCClientHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if te := env.TracingEngine(); te != nil {
				if h := te.GRPCClientHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if h := runtime.CombineGRPCStatsHandlers(statsHandlers...); h != nil {
				opts = append(opts, grpc.WithStatsHandler(h))
			}
			target := cfg.Address
			if connectionsCount > 1 {
				builder := manual.NewBuilderWithScheme(fmt.Sprintf("servicelib-%d", cfg.ID))
				address := strings.TrimPrefix(cfg.Address, "dns:///")
				address = strings.TrimPrefix(address, "passthrough:///")
				addresses := make([]resolver.Address, connectionsCount)
				for index := range addresses {
					addresses[index] = resolver.Address{
						Addr:       address,
						Attributes: attributes.New("servicelib.connection-index", index),
					}
				}
				builder.InitialState(resolver.State{Addresses: addresses})
				target = builder.Scheme() + ":///" + cfg.Name
				opts = append(
					opts,
					grpc.WithResolvers(builder),
					grpc.WithDefaultServiceConfig(`{"loadBalancingConfig":[{"round_robin":{}}]}`),
				)
			}
			conn, connErr := grpc.NewClient(target, opts...)
			if connErr != nil {
				return nil, nil, fmt.Errorf("gRPC client did not connect to server 'Inventory Service API': %w", connErr)
			}
			return conn, inventoryserviceapi.NewInventoryServiceApiClient(conn), nil
		}
	}

	if makers.orderProcessOrderItemsMaker == nil {
		makers.orderProcessOrderItemsMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*order.ProcessOrderItems, error) {
			return order.MakeProcessOrderItems(ctx, env)
		}
	}
	if makers.orderMapOrderItemResultToOrderStateMaker == nil {
		makers.orderMapOrderItemResultToOrderStateMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*order.MapOrderItemResultToOrderState, error) {
			return order.MakeMapOrderItemResultToOrderState(ctx, env)
		}
	}
	if makers.orderSoftDeadlineMaker == nil {
		makers.orderSoftDeadlineMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*order.SoftDeadline, error) {
			return order.MakeSoftDeadline(ctx, env)
		}
	}
	if makers.orderMapToOrderStateMaker == nil {
		makers.orderMapToOrderStateMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*order.MapToOrderState, error) {
			return order.MakeMapToOrderState(ctx, env)
		}
	}
	if makers.orderMapToOrderProcessedMaker == nil {
		makers.orderMapToOrderProcessedMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*order.MapToOrderProcessed, error) {
			return order.MakeMapToOrderProcessed(ctx, env)
		}
	}

	if makers.endpointProcessOrderSourceMaker == nil {
		makers.endpointProcessOrderSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.ProcessOrderSource, error) {
			return endpoint.MakeProcessOrderSource(ctx, env)
		}
	}

	if makers.endpointProcessOrderItemSinkMaker == nil {
		makers.endpointProcessOrderItemSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSink, error) {
			return endpoint.MakeProcessOrderItemSink(ctx, env)
		}
	}
	if makers.endpointOrderProcessedEndpointSinkMaker == nil {
		makers.endpointOrderProcessedEndpointSinkMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSink, error) {
			return endpoint.MakeOrderProcessedEndpointSink(ctx, env)
		}
	}

	return nil
}
