// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"

	"github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi/processorderitem"
	types2 "github.com/gorundebug/model_go/pkg/types"
	"github.com/gorundebug/orderservice/internal/config"
	"github.com/gorundebug/orderservice/internal/functions/endpoint"
	"github.com/gorundebug/orderservice/internal/functions/order"
	"github.com/gorundebug/orderservice/internal/types"
	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	"github.com/gorundebug/servicelib/transformation"
)

type orderPipelineMakers struct {
	// stream function makers
	orderProcessOrderItemsMaker              func(ctx context.Context, cfg *runtimecfg.FlatMapStreamConfig, env environment.ServiceEnvironment) (*order.ProcessOrderItems, error)
	orderMapOrderItemResultToOrderStateMaker func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapOrderItemResultToOrderState, error)
	orderSoftDeadlineMaker                   func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*order.SoftDeadline, error)
	orderMapToOrderStateMaker                func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapToOrderState, error)
	orderMapToOrderProcessedMaker            func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapToOrderProcessed, error)
	// data source function makers
	endpointProcessOrderSourceMaker func(ctx context.Context, cfg *runtimecfg.HttpEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderSource, error)
	// data sink function makers
	endpointProcessOrderItemSinkMaker       func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSink, error)
	endpointOrderProcessedEndpointSinkMaker func(ctx context.Context, cfg *runtimecfg.KafkaEndpointConfig, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSink, error)
}

type orderPipelineFunctions struct {
	// stream functions
	orderProcessOrderItems              *order.ProcessOrderItems
	orderMapOrderItemResultToOrderState *order.MapOrderItemResultToOrderState
	orderSoftDeadline                   *order.SoftDeadline
	orderMapToOrderState                *order.MapToOrderState
	orderMapToOrderProcessed            *order.MapToOrderProcessed
	// data source functions
	endpointProcessOrderSource *endpoint.ProcessOrderSource
	// data sink functions
	endpointProcessOrderItemSink       *endpoint.ProcessOrderItemSink
	endpointOrderProcessedEndpointSink *endpoint.OrderProcessedEndpointSink
}

type orderPipelineStreams struct {
	processOrder                   runtime.TypedInputStream[*types.Order, *types.OrderState, error]
	splitPipeline                  runtime.TypedSplitStream[*types.Order]
	processOrderItems              runtime.TypedTransformConsumedStream[*types.Order, *types2.OrderItem]
	processOrderItem               runtime.TypedSinkStreamWithResult[*types2.OrderItem, *types2.OrderItemResult, *types.OrderState]
	processOrderItemError          runtime.TypedConsumedStream[*types.OrderState]
	mapOrderItemResultToOrderState runtime.TypedTransformConsumedStream[*types2.OrderItemResult, *types.OrderState]
	softDeadline                   runtime.TypedConsumedStream[*types.Order]
	mapToOrderState                runtime.TypedTransformConsumedStream[*types.Order, *types.OrderState]
	mergeResults                   runtime.TypedConsumedStream[*types.OrderState]
	splitOrderResult               runtime.TypedSplitStream[*types.OrderState]
	mapToOrderProcessed            runtime.TypedTransformConsumedStream[*types.OrderState, *types2.OrderProcessed]
	publishOrderProcessed          runtime.TypedSinkStream[*types2.OrderProcessed, error]
}

type orderPipelineHandlers struct {
	// data source handlers
	endpointProcessOrderSource endpoint.ProcessOrderSourceType
}

type orderPipelineDataConnectors struct {
	// data sources
	processOrder runtime.Consumer[*types.Order]
	// data sinks
	processOrderItemProcessOrderItem    runtime.Consumer[*types2.OrderItem]
	publishOrderProcessedOrderProcessed runtime.Consumer[*types2.OrderProcessed]
}

func (s *Service) initOrderMakers() {
	if s.makers.orderProcessOrderItemsMaker == nil {
		s.makers.orderProcessOrderItemsMaker = func(ctx context.Context, cfg *runtimecfg.FlatMapStreamConfig, env environment.ServiceEnvironment) (*order.ProcessOrderItems, error) {
			return order.MakeProcessOrderItems(ctx, env, cfg)
		}
	}
	if s.makers.orderMapOrderItemResultToOrderStateMaker == nil {
		s.makers.orderMapOrderItemResultToOrderStateMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapOrderItemResultToOrderState, error) {
			return order.MakeMapOrderItemResultToOrderState(ctx, env, cfg)
		}
	}
	if s.makers.orderSoftDeadlineMaker == nil {
		s.makers.orderSoftDeadlineMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*order.SoftDeadline, error) {
			return order.MakeSoftDeadline(ctx, env, cfg)
		}
	}
	if s.makers.orderMapToOrderStateMaker == nil {
		s.makers.orderMapToOrderStateMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapToOrderState, error) {
			return order.MakeMapToOrderState(ctx, env, cfg)
		}
	}
	if s.makers.orderMapToOrderProcessedMaker == nil {
		s.makers.orderMapToOrderProcessedMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapToOrderProcessed, error) {
			return order.MakeMapToOrderProcessed(ctx, env, cfg)
		}
	}
	if s.makers.endpointProcessOrderSourceMaker == nil {
		s.makers.endpointProcessOrderSourceMaker = func(ctx context.Context, cfg *runtimecfg.HttpEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderSource, error) {
			return endpoint.MakeProcessOrderSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointProcessOrderItemSinkMaker == nil {
		s.makers.endpointProcessOrderItemSinkMaker = func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSink, error) {
			return endpoint.MakeProcessOrderItemSink(ctx, env, cfg)
		}
	}
	if s.makers.endpointOrderProcessedEndpointSinkMaker == nil {
		s.makers.endpointOrderProcessedEndpointSinkMaker = func(ctx context.Context, cfg *runtimecfg.KafkaEndpointConfig, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSink, error) {
			return endpoint.MakeOrderProcessedEndpointSink(ctx, env, cfg)
		}
	}
}

// initOrderStreams constructs the streams owned by this
// pipeline. The service-level coordinator preserves the global construction,
// binding and post-initialization phases across all pipelines.
func (s *Service) initOrderStreams(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx
	_ = cfg
	_ = env
	if err = s.initOrderProcessOrderStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderSplitPipelineStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderProcessOrderItemsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderProcessOrderItemStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderMapOrderItemResultToOrderStateStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderSoftDeadlineStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderMapToOrderStateStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderMergeResultsStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderSplitOrderResultStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderMapToOrderProcessedStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initOrderPublishOrderProcessedStream(ctx, cfg, env); err != nil {
		return err
	}
	return nil
}

func (s *Service) bindOrderStreams() error {
	if err := s.bindOrderProcessOrderStream(); err != nil {
		return err
	}
	return nil
}

func (s *Service) initOrderEndpoints() error {
	var err error
	if s.dataConnectors.processOrder, s.handlers.endpointProcessOrderSource, err = endpoint.MakeEndpointConsumerProcessOrderSource(s.streams.processOrder, s.functions.endpointProcessOrderSource); err != nil {
		return err
	}
	if s.dataConnectors.processOrderItemProcessOrderItem, err = endpoint.MakeEndpointConsumerProcessOrderItemSink(s.streams.processOrderItem, s.functions.endpointProcessOrderItemSink, func(ctx context.Context, req *processorderitem.ProcessOrderItemRequest) (*processorderitem.ProcessOrderItemResponse, error) {
		return s.inventoryServiceApiGrpcClient.ProcessOrderItem(ctx, req)
	}); err != nil {
		return err
	}
	if s.dataConnectors.publishOrderProcessedOrderProcessed, err = endpoint.MakeEndpointConsumerOrderProcessedEndpointSink(s.streams.publishOrderProcessed, s.functions.endpointOrderProcessedEndpointSink); err != nil {
		return err
	}
	_ = err
	return nil
}

func (s *Service) postInitOrderStreams() error {
	return nil
}
func (s *Service) initOrderProcessOrderStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.processOrder, err = transformation.Input[*types.Order, *types.OrderState, error](&cfg.Streams.ProcessOrder, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) bindOrderProcessOrderStream() error {
	return s.streams.processOrder.SetSource(s.streams.splitOrderResult.AddStream())
}
func (s *Service) initOrderSplitPipelineStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.splitPipeline, err = transformation.Split[*types.Order](&cfg.Streams.SplitPipeline, s.streams.processOrder); err != nil {
		return err
	}
	return nil
}
func (s *Service) initOrderProcessOrderItemsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.processOrderItems, err = transformation.FlatMap[*types.Order, *types2.OrderItem](&cfg.Streams.ProcessOrderItems, s.streams.splitPipeline.AddStream(), s.functions.orderProcessOrderItems); err != nil {
		return err
	}
	return nil
}
func (s *Service) initOrderProcessOrderItemStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.processOrderItem, err = transformation.SinkWithResult[*types2.OrderItem, *types2.OrderItemResult, *types.OrderState](&cfg.Streams.ProcessOrderItem, s.streams.processOrderItems); err != nil {
		return err
	}
	s.streams.processOrderItemError = s.streams.processOrderItem.GetErrorStream()
	return nil
}
func (s *Service) initOrderMapOrderItemResultToOrderStateStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.mapOrderItemResultToOrderState, err = transformation.Map[*types2.OrderItemResult, *types.OrderState](&cfg.Streams.MapOrderItemResultToOrderState, s.streams.processOrderItem, s.functions.orderMapOrderItemResultToOrderState); err != nil {
		return err
	}
	return nil
}
func (s *Service) initOrderSoftDeadlineStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.softDeadline, err = transformation.Delay[*types.Order](&cfg.Streams.SoftDeadline, s.streams.splitPipeline.AddStream(), s.functions.orderSoftDeadline); err != nil {
		return err
	}
	return nil
}
func (s *Service) initOrderMapToOrderStateStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.mapToOrderState, err = transformation.Map[*types.Order, *types.OrderState](&cfg.Streams.MapToOrderState, s.streams.softDeadline, s.functions.orderMapToOrderState); err != nil {
		return err
	}
	return nil
}
func (s *Service) initOrderMergeResultsStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.mergeResults, err = transformation.Merge[*types.OrderState](&cfg.Streams.MergeResults, s.streams.mapToOrderState, s.streams.mapOrderItemResultToOrderState, s.streams.processOrderItemError); err != nil {
		return err
	}
	return nil
}
func (s *Service) initOrderSplitOrderResultStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.splitOrderResult, err = transformation.Split[*types.OrderState](&cfg.Streams.SplitOrderResult, s.streams.mergeResults); err != nil {
		return err
	}
	return nil
}
func (s *Service) initOrderMapToOrderProcessedStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.mapToOrderProcessed, err = transformation.Map[*types.OrderState, *types2.OrderProcessed](&cfg.Streams.MapToOrderProcessed, s.streams.splitOrderResult.AddStream(), s.functions.orderMapToOrderProcessed); err != nil {
		return err
	}
	return nil
}
func (s *Service) initOrderPublishOrderProcessedStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.publishOrderProcessed, err = transformation.Sink[*types2.OrderProcessed, error](&cfg.Streams.PublishOrderProcessed, s.streams.mapToOrderProcessed); err != nil {
		return err
	}
	return nil
}
func (s *Service) scheduleOrderFunctions(
	eg pipelineMakerTaskGroup,
	egCtx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) {
	if s.makers.orderProcessOrderItemsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderProcessOrderItems, err = s.makers.orderProcessOrderItemsMaker(egCtx, &cfg.Streams.ProcessOrderItems, env)
			return err
		})
	}
	if s.makers.orderMapOrderItemResultToOrderStateMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderMapOrderItemResultToOrderState, err = s.makers.orderMapOrderItemResultToOrderStateMaker(egCtx, &cfg.Streams.MapOrderItemResultToOrderState, env)
			return err
		})
	}
	if s.makers.orderSoftDeadlineMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderSoftDeadline, err = s.makers.orderSoftDeadlineMaker(egCtx, &cfg.Streams.SoftDeadline, env)
			return err
		})
	}
	if s.makers.orderMapToOrderStateMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderMapToOrderState, err = s.makers.orderMapToOrderStateMaker(egCtx, &cfg.Streams.MapToOrderState, env)
			return err
		})
	}
	if s.makers.orderMapToOrderProcessedMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderMapToOrderProcessed, err = s.makers.orderMapToOrderProcessedMaker(egCtx, &cfg.Streams.MapToOrderProcessed, env)
			return err
		})
	}
	if s.makers.endpointProcessOrderSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointProcessOrderSource, err = s.makers.endpointProcessOrderSourceMaker(egCtx, &cfg.Endpoints.ProcessOrder, env)
			return err
		})
	}
	if s.makers.endpointProcessOrderItemSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointProcessOrderItemSink, err = s.makers.endpointProcessOrderItemSinkMaker(egCtx, &cfg.Endpoints.ProcessOrderItem, env)
			return err
		})
	}
	if s.makers.endpointOrderProcessedEndpointSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointOrderProcessedEndpointSink, err = s.makers.endpointOrderProcessedEndpointSinkMaker(egCtx, &cfg.Endpoints.OrderProcessed, env)
			return err
		})
	}
}
