// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"reflect"
	"sync"
	"syscall"
	"time"

	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	log "github.com/gorundebug/servicelib/runtime/environment/log"
	"github.com/gorundebug/servicelib/runtime/environment/tracing"
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"
	"github.com/gorundebug/servicelib/transformation"
	"golang.org/x/sync/errgroup"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	"github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi"
	"github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi/processorderitem"
	serdes2 "github.com/gorundebug/model/pkg/serdes"
	types2 "github.com/gorundebug/model/pkg/types"
	"github.com/gorundebug/order_service_api/pkg/generated/openapi/orderserviceapi"
	"github.com/gorundebug/orderservice/internal/config"
	"github.com/gorundebug/orderservice/internal/functions"
	"github.com/gorundebug/orderservice/internal/serdes"
	"github.com/gorundebug/orderservice/internal/types"
)

type serviceMakers struct {
	//stream function makers
	processOrderItemsMaker              func(ctx context.Context, cfg *runtimecfg.FlatMapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessOrderItems, error)
	mapOrderItemResultToOrderStateMaker func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.MapOrderItemResultToOrderState, error)
	softDeadlineMaker                   func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.SoftDeadline, error)
	mapToOrderStateMaker                func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.MapToOrderState, error)
	//data source function makers
	processOrderMaker func(ctx context.Context, cfg *runtimecfg.HttpEndpointConfig, env environment.ServiceEnvironment) (*functions.ProcessOrder, error)
	//data sink function makers
	processOrderItemMaker func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*functions.ProcessOrderItemSink, error)
}

type serviceFunctions struct {
	//stream functions
	processOrderItems              *functions.ProcessOrderItems
	mapOrderItemResultToOrderState *functions.MapOrderItemResultToOrderState
	softDeadline                   *functions.SoftDeadline
	mapToOrderState                *functions.MapToOrderState
	//data source functions
	processOrder *functions.ProcessOrder
	//data sink functions
	processOrderItem *functions.ProcessOrderItemSink
}

type serviceStreams struct {
	//streams
	processOrder                   runtime.TypedInputStream[*types.Order, *types.OrderState, error]
	splitPipeline                  runtime.TypedSplitStream[*types.Order]
	processOrderItems              runtime.TypedTransformConsumedStream[*types.Order, *types2.OrderItem]
	processOrderItem               runtime.TypedSinkStreamWithResult[*types2.OrderItem, *types2.OrderItemResult, error]
	mapOrderItemResultToOrderState runtime.TypedTransformConsumedStream[*types2.OrderItemResult, *types.OrderState]
	softDeadline                   runtime.TypedConsumedStream[*types.Order]
	mapToOrderState                runtime.TypedTransformConsumedStream[*types.Order, *types.OrderState]
	mergeResults                   runtime.TypedConsumedStream[*types.OrderState]
}

type serviceHandlers struct {
	//data source handlers
	processOrder functions.ProcessOrderType
}

type serviceDataConnectors struct {
	//data sources
	processOrder runtime.Consumer[*types.Order]
	//data sinks
	processOrderItemProcessOrderItem runtime.Consumer[*types2.OrderItem]
}

type Service struct {
	runtime.ServiceApp
	makers                             serviceMakers
	functions                          serviceFunctions
	streams                            serviceStreams
	handlers                           serviceHandlers
	dataConnectors                     serviceDataConnectors
	httpServer                         *http.Server
	httpServerMaker                    func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMux                            *http.ServeMux
	httpMuxMaker                       func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)
	httpServerDone                     chan struct{}
	inventoryServiceApiGrpcClientMaker func(context.Context, *runtimecfg.GrpcDataConnectorConfig, runtime.RuntimeEnvironment) (*grpc.ClientConn, inventoryserviceapi.InventoryServiceApiClient, error)
	inventoryServiceApiGrpcClientConn  *grpc.ClientConn
	inventoryServiceApiGrpcClient      inventoryserviceapi.InventoryServiceApiClient
}

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	case runtimeserde.GetSerdeType[types.OrderState](), runtimeserde.GetSerdeType[*types.OrderState]():
		{
			var serde runtimeserde.Serde[*types.OrderState] = &serdes.OrderStateSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types.Order](), runtimeserde.GetSerdeType[*types.Order]():
		{
			var serde runtimeserde.Serde[*types.Order] = &serdes.OrderSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderItem](), runtimeserde.GetSerdeType[*types2.OrderItem]():
		{
			var serde runtimeserde.Serde[*types2.OrderItem] = &serdes2.OrderItemSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderItemResult](), runtimeserde.GetSerdeType[*types2.OrderItemResult]():
		{
			var serde runtimeserde.Serde[*types2.OrderItemResult] = &serdes2.OrderItemResultSerde{}
			return serde, nil
		}

	}
	return nil, nil
}

func (s *Service) RegisterHTTPHandler(path string, handler http.Handler) {
	if s.httpMux != nil {
		s.httpMux.Handle(path, s.httpHandlerMiddleware(path, handler))
	} else {
		s.ServiceApp.RegisterHTTPHandler(path, s.httpHandlerMiddleware(path, handler))
	}
}

func (s *Service) Config() *config.Config {
	return s.ServiceApp.GetConfig().(*config.Config)
}

func (s *Service) initMakers(ctx context.Context) error {
	s.httpMuxMaker = func(_ context.Context, _ runtime.RuntimeEnvironment) (*http.ServeMux, error) {
		return http.NewServeMux(), nil
	}
	if s.inventoryServiceApiGrpcClientMaker == nil {
		s.inventoryServiceApiGrpcClientMaker = func(ctx context.Context, cfg *runtimecfg.GrpcDataConnectorConfig, env runtime.RuntimeEnvironment) (*grpc.ClientConn, inventoryserviceapi.InventoryServiceApiClient, error) {
			opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}
			if te := env.TracingEngine(); te != nil {
				if h := te.GRPCClientHandler(); h != nil {
					opts = append(opts, grpc.WithStatsHandler(h))
				}
			}
			if me := env.MetricsEngine(); me != nil {
				if h := me.GRPCClientHandler(); h != nil {
					opts = append(opts, grpc.WithStatsHandler(h))
				}
			}
			conn, connErr := grpc.NewClient(cfg.Address, opts...)
			if connErr != nil {
				return nil, nil, fmt.Errorf("gRPC client did not connect to server 'Inventory Service API': %w", connErr)
			}
			return conn, inventoryserviceapi.NewInventoryServiceApiClient(conn), nil
		}
	}
	if s.makers.processOrderItemsMaker == nil {
		s.makers.processOrderItemsMaker = func(ctx context.Context, cfg *runtimecfg.FlatMapStreamConfig, env environment.ServiceEnvironment) (*functions.ProcessOrderItems, error) {
			return functions.MakeProcessOrderItems(ctx, env, cfg)
		}
	}
	if s.makers.mapOrderItemResultToOrderStateMaker == nil {
		s.makers.mapOrderItemResultToOrderStateMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.MapOrderItemResultToOrderState, error) {
			return functions.MakeMapOrderItemResultToOrderState(ctx, env, cfg)
		}
	}
	if s.makers.softDeadlineMaker == nil {
		s.makers.softDeadlineMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*functions.SoftDeadline, error) {
			return functions.MakeSoftDeadline(ctx, env, cfg)
		}
	}
	if s.makers.mapToOrderStateMaker == nil {
		s.makers.mapToOrderStateMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*functions.MapToOrderState, error) {
			return functions.MakeMapToOrderState(ctx, env, cfg)
		}
	}
	if s.makers.processOrderMaker == nil {
		s.makers.processOrderMaker = func(ctx context.Context, cfg *runtimecfg.HttpEndpointConfig, env environment.ServiceEnvironment) (*functions.ProcessOrder, error) {
			return functions.MakeProcessOrder(ctx, env, cfg)
		}
	}
	if s.makers.processOrderItemMaker == nil {
		s.makers.processOrderItemMaker = func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*functions.ProcessOrderItemSink, error) {
			return functions.MakeProcessOrderItemSink(ctx, env, cfg)
		}
	}

	return nil
}

func (s *Service) buildRuntime(ctx context.Context) error {
	cfg := s.Config()

	if err := s.initMakers(ctx); err != nil {
		return fmt.Errorf("init makers failed: %w", err)
	}

	if err := s.customMakersInit(ctx); err != nil {
		return fmt.Errorf("custom init makers failed: %w", err)
	}

	var err error

	if s.httpMuxMaker != nil {
		if s.httpMux, err = s.httpMuxMaker(ctx, s); err != nil {
			return fmt.Errorf("create http mux failed: %w", err)
		}
	}
	if err := s.initGrpcClients(ctx); err != nil {
		return fmt.Errorf("init gRPC clients failed: %w", err)
	}

	if err := s.initFunctions(ctx, cfg); err != nil {
		return fmt.Errorf("init functions failed: %w", err)
	}

	if err := s.customFunctionsInit(ctx); err != nil {
		return fmt.Errorf("custom functions init failed: %w", err)
	}

	if err := s.initStreams(ctx); err != nil {
		return fmt.Errorf("init streams failed: %w", err)
	}

	return nil
}

func (s *Service) initStreams(ctx context.Context) error {
	cfg := s.Config()
	var err error
	if s.streams.processOrder, err = transformation.Input[*types.Order, *types.OrderState, error](&cfg.Streams.ProcessOrder, s); err != nil {
		return err
	}
	if s.streams.splitPipeline, err = transformation.Split[*types.Order](&cfg.Streams.SplitPipeline, s.streams.processOrder); err != nil {
		return err
	}
	if s.streams.processOrderItems, err = transformation.FlatMap[*types.Order, *types2.OrderItem](&cfg.Streams.ProcessOrderItems, s.streams.splitPipeline.AddStream(), s.functions.processOrderItems); err != nil {
		return err
	}
	if s.streams.processOrderItem, err = transformation.SinkWithResult[*types2.OrderItem, *types2.OrderItemResult, error](&cfg.Streams.ProcessOrderItem, s.streams.processOrderItems); err != nil {
		return err
	}
	if s.streams.mapOrderItemResultToOrderState, err = transformation.Map[*types2.OrderItemResult, *types.OrderState](&cfg.Streams.MapOrderItemResultToOrderState, s.streams.processOrderItem, s.functions.mapOrderItemResultToOrderState); err != nil {
		return err
	}
	if s.streams.softDeadline, err = transformation.Delay[*types.Order](&cfg.Streams.SoftDeadline, s.streams.splitPipeline.AddStream(), s.functions.softDeadline); err != nil {
		return err
	}
	if s.streams.mapToOrderState, err = transformation.Map[*types.Order, *types.OrderState](&cfg.Streams.MapToOrderState, s.streams.softDeadline, s.functions.mapToOrderState); err != nil {
		return err
	}
	if s.streams.mergeResults, err = transformation.Merge[*types.OrderState](&cfg.Streams.MergeResults, s.streams.mapToOrderState, s.streams.mapOrderItemResultToOrderState); err != nil {
		return err
	}
	if err = s.streams.processOrder.SetSource(s.streams.mergeResults); err != nil {
		return err
	}
	if s.dataConnectors.processOrder, s.handlers.processOrder, err = functions.MakeEndpointConsumerProcessOrder(s.streams.processOrder, s.functions.processOrder); err != nil {
		return err
	}
	if s.dataConnectors.processOrderItemProcessOrderItem, err = functions.MakeEndpointConsumerProcessOrderItemSink(s.streams.processOrderItem, s.functions.processOrderItem, func(ctx context.Context, req *processorderitem.ProcessOrderItemRequest) (*processorderitem.ProcessOrderItemResponse, error) {
		return s.inventoryServiceApiGrpcClient.ProcessOrderItem(ctx, req)
	}); err != nil {
		return err
	}
	_ = err
	_ = cfg
	return nil
}
func (s *Service) HasCustomHTTPServer() bool {
	return true
}

func (s *Service) initFunctions(ctx context.Context, cfg *config.Config) error {
	eg, egCtx := errgroup.WithContext(ctx)
	if s.makers.processOrderItemsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processOrderItems, err = s.makers.processOrderItemsMaker(egCtx, &cfg.Streams.ProcessOrderItems, s)
			return err
		})
	}
	if s.makers.mapOrderItemResultToOrderStateMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.mapOrderItemResultToOrderState, err = s.makers.mapOrderItemResultToOrderStateMaker(egCtx, &cfg.Streams.MapOrderItemResultToOrderState, s)
			return err
		})
	}
	if s.makers.softDeadlineMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.softDeadline, err = s.makers.softDeadlineMaker(egCtx, &cfg.Streams.SoftDeadline, s)
			return err
		})
	}
	if s.makers.mapToOrderStateMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.mapToOrderState, err = s.makers.mapToOrderStateMaker(egCtx, &cfg.Streams.MapToOrderState, s)
			return err
		})
	}
	if s.makers.processOrderMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processOrder, err = s.makers.processOrderMaker(egCtx, &cfg.Endpoints.ProcessOrder, s)
			return err
		})
	}
	if s.makers.processOrderItemMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.processOrderItem, err = s.makers.processOrderItemMaker(egCtx, &cfg.Endpoints.ProcessOrderItem, s)
			return err
		})
	}
	if err := eg.Wait(); err != nil {
		return err
	}
	return nil
}
func (s *Service) initGrpcClients(ctx context.Context) error {
	cfg := s.Config()
	eg, egCtx := errgroup.WithContext(ctx)
	eg.Go(func() error {
		conn, client, err := s.inventoryServiceApiGrpcClientMaker(egCtx, &cfg.DataConnectors.InventoryServiceApi, s)
		if err != nil {
			return fmt.Errorf("init gRPC client for 'Inventory Service API' failed: %w", err)
		}
		s.inventoryServiceApiGrpcClientConn = conn
		s.inventoryServiceApiGrpcClient = client
		return nil
	})
	return eg.Wait()
}

func (s *Service) ServiceInit() error {
	if s.httpMux == nil {
		s.httpMux = http.NewServeMux()
	}
	return nil
}

func (s *Service) StartService(ctx context.Context) error {

	if err := s.buildRuntime(ctx); err != nil {
		return fmt.Errorf("build runtime failed: %w", err)
	}

	if err := s.start(ctx); err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}

	if err := s.ServiceApp.Start(ctx); err != nil {
		return fmt.Errorf("service app start failed: %w", err)
	}

	var err error

	httpSvc := &HttpService{service: s}
	orderserviceapi.HandlerFromMux(httpSvc, s.httpMux)
	s.RegisterHTTPHandler("/swagger/orderserviceapi/", orderserviceapi.SwaggerHandler("/swagger/orderserviceapi/"))

	if s.httpMux != nil {
		if s.httpServerMaker != nil {
			if s.httpServer, err = s.httpServerMaker(ctx, s); err != nil {
				return fmt.Errorf("create http server failed: %w", err)
			}
		}
		if s.httpServer == nil {
			svcCfg := s.ServiceConfig()
			handler := http.Handler(s.httpMux)
			te := s.TracingEngine()
			if te != nil {
				handler = te.HTTPServerHandler(handler, runtime.ToSnakeCase(svcCfg.Name))
			}
			if me := s.MetricsEngine(); me != nil {
				handler = me.HTTPServerHandler(handler, runtime.ToSnakeCase(svcCfg.Name))
			}
			if te != nil {
				inner := handler
				handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
					if r.Header.Get("X-Trace") != "" {
						r = r.WithContext(tracing.EnableSampling(r.Context()))
					}
					inner.ServeHTTP(w, r)
				})
			}
			s.httpServer = &http.Server{
				Addr:    fmt.Sprintf("%s:%d", svcCfg.HttpHost, svcCfg.HttpPort),
				Handler: handler,
			}
		}
	}
	if s.httpServer != nil {
		s.httpServerDone = make(chan struct{})
		ln, err := net.Listen("tcp", s.httpServer.Addr)
		if err != nil {
			return fmt.Errorf("failed to listen http port: %v", err)
		}
		go func() {
			s.Log().Info(ctx, "HTTP server listening", log.Any("addr", s.httpServer.Addr))
			if err := s.httpServer.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
				s.Log().Error(ctx, "HTTP server stopped unexpectedly", log.Err(err))
			}
			close(s.httpServerDone)
		}()
	}
	return nil
}

func (s *Service) StopService(ctx context.Context) {
	svcCfg := s.ServiceConfig()
	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(svcCfg.ShutdownTimeout)*time.Millisecond)
	defer cancel()
	wg := sync.WaitGroup{}
	done := make(chan struct{})
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.ServiceApp.Stop(timeoutCtx)
	}()

	inventoryServiceApiGrpcClientStopDone := make(chan struct{})
	wg.Add(1)
	go func() {
		defer wg.Done()
		defer close(inventoryServiceApiGrpcClientStopDone)
		if err := s.inventoryServiceApiGrpcClientConn.Close(); err != nil {
			s.Log().Warn(timeoutCtx, "gRPC client close error", log.Err(err))
		}
	}()

	var httpStopDone chan struct{}
	if s.httpServer != nil {
		httpStopDone = make(chan struct{})
		wg.Add(1)
		go func() {
			defer wg.Done()
			defer close(httpStopDone)
			if err := s.httpServer.Shutdown(timeoutCtx); err != nil {
				s.Log().Warn(timeoutCtx, "HTTP server shutdown", log.Err(err))
			}
			<-s.httpServerDone
		}()
	}
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.stop(timeoutCtx)
	}()
	go func() {
		wg.Wait()
		close(done)
	}()
	select {
	case <-done:
	case <-timeoutCtx.Done():
		if httpStopDone != nil {
			select {
			case <-httpStopDone:
			default:
				s.Log().Warn(timeoutCtx, "HTTP server stop timed out", log.Err(timeoutCtx.Err()))
			}
		}
		select {
		case <-inventoryServiceApiGrpcClientStopDone:
		default:
			s.Log().Warn(timeoutCtx, "gRPC client to server stop timed out", log.Str("server", "Inventory Service API"), log.Err(timeoutCtx.Err()))
		}

	}
}

func Start(ctx context.Context,
	dependency environment.ServiceDependencies,
	done <-chan struct{},
	configPath *string,
	valuesPath *string,
	version string,
	commit string,
) error {
	if dependency == nil {
		dependency = &serviceDependencies{}
	}

	service, err := runtime.MakeService[*Service,
		*config.Config](
		ctx,
		"Order Service",
		dependency,
		configPath,
		valuesPath,
		func() *Service { return &Service{} },
		func() *config.Config { return config.MakeConfig() },
	)
	if err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}
	defer service.Release()

	service.Log().Info(ctx, "starting service", log.Str("service", service.ServiceConfig().Name), log.Str("version", version), log.Str("commit", commit))

	var stop chan os.Signal
	if done == nil {
		stop = make(chan os.Signal, 2)
		signal.Notify(stop, syscall.SIGINT)
		signal.Notify(stop, syscall.SIGTERM)
	}

	if ctx == nil {
		localCtx, cancel := context.WithCancel(context.Background())
		defer cancel()

		ctx = localCtx
	}

	if err = service.StartService(ctx); err != nil {
		return fmt.Errorf("start service failed: %w", err)
	}
	service.Log().Info(ctx, "service started", log.Str("service", service.ServiceConfig().Name))

	if os.Getenv("GORUNDEBUG_TEST") != "" && stop != nil {
		time.AfterFunc(1*time.Second, func() {
			close(stop)
		})
	}
	if stop != nil {
		<-stop
	} else if done != nil {
		<-done
	}
	service.Log().Info(ctx, "service stop signal received", log.Str("service", service.ServiceConfig().Name))
	service.StopService(context.WithoutCancel(ctx))
	service.Log().Info(ctx, "service stopped", log.Str("service", service.ServiceConfig().Name))
	return nil
}
