// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"reflect"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	log "github.com/gorundebug/servicelib/runtime/environment/log"
	"github.com/gorundebug/servicelib/runtime/environment/tracing"
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"
	"github.com/gorundebug/servicelib/transformation"
	"golang.org/x/sync/errgroup"
	"google.golang.org/grpc"
	"google.golang.org/grpc/attributes"
	_ "google.golang.org/grpc/balancer/roundrobin"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/resolver"
	"google.golang.org/grpc/resolver/manual"
	"google.golang.org/grpc/stats"

	"github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi"
	"github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi/processorderitem"
	serdes2 "github.com/gorundebug/model_go/pkg/serdes"
	types2 "github.com/gorundebug/model_go/pkg/types"
	"github.com/gorundebug/order_service_api/pkg/generated/openapi/orderserviceapi"
	"github.com/gorundebug/orderservice/internal/config"
	"github.com/gorundebug/orderservice/internal/functions/endpoint"
	"github.com/gorundebug/orderservice/internal/functions/order"
	"github.com/gorundebug/orderservice/internal/serdes"
	"github.com/gorundebug/orderservice/internal/types"
)

type serviceMakers struct {
	//stream function makers
	orderProcessOrderItemsMaker              func(ctx context.Context, cfg *runtimecfg.FlatMapStreamConfig, env environment.ServiceEnvironment) (*order.ProcessOrderItems, error)
	orderMapOrderItemResultToOrderStateMaker func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapOrderItemResultToOrderState, error)
	orderSoftDeadlineMaker                   func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*order.SoftDeadline, error)
	orderMapToOrderStateMaker                func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapToOrderState, error)
	orderMapToOrderProcessedMaker            func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapToOrderProcessed, error)
	//data source function makers
	endpointProcessOrderSourceMaker func(ctx context.Context, cfg *runtimecfg.HttpEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderSource, error)
	//data sink function makers
	endpointProcessOrderItemSinkMaker       func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSink, error)
	endpointOrderProcessedEndpointSinkMaker func(ctx context.Context, cfg *runtimecfg.KafkaEndpointConfig, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSink, error)
}

type serviceFunctions struct {
	//stream functions
	orderProcessOrderItems              *order.ProcessOrderItems
	orderMapOrderItemResultToOrderState *order.MapOrderItemResultToOrderState
	orderSoftDeadline                   *order.SoftDeadline
	orderMapToOrderState                *order.MapToOrderState
	orderMapToOrderProcessed            *order.MapToOrderProcessed
	//data source functions
	endpointProcessOrderSource *endpoint.ProcessOrderSource
	//data sink functions
	endpointProcessOrderItemSink       *endpoint.ProcessOrderItemSink
	endpointOrderProcessedEndpointSink *endpoint.OrderProcessedEndpointSink
}

type serviceStreams struct {
	//streams
	processOrder                   runtime.TypedInputStream[*types.Order, *types.OrderState, error]
	splitPipeline                  runtime.TypedSplitStream[*types.Order]
	processOrderItems              runtime.TypedTransformConsumedStream[*types.Order, *types2.OrderItem]
	processOrderItem               runtime.TypedSinkStreamWithResult[*types2.OrderItem, *types2.OrderItemResult, *types.OrderState]
	processOrderItemError          runtime.TypedConsumedStream[*types.OrderState]
	mapOrderItemResultToOrderState runtime.TypedTransformConsumedStream[*types2.OrderItemResult, *types.OrderState]
	softDeadline                   runtime.TypedConsumedStream[*types.Order]
	mapToOrderState                runtime.TypedTransformConsumedStream[*types.Order, *types.OrderState]
	mergeResults                   runtime.TypedConsumedStream[*types.OrderState]
	splitOrderResult               runtime.TypedSplitStream[*types.OrderState]
	mapToOrderProcessed            runtime.TypedTransformConsumedStream[*types.OrderState, *types2.OrderProcessed]
	publishOrderProcessed          runtime.TypedSinkStream[*types2.OrderProcessed, error]
}

type serviceHandlers struct {
	//data source handlers
	endpointProcessOrderSource endpoint.ProcessOrderSourceType
}

type serviceDataConnectors struct {
	//data sources
	processOrder runtime.Consumer[*types.Order]
	//data sinks
	processOrderItemProcessOrderItem    runtime.Consumer[*types2.OrderItem]
	publishOrderProcessedOrderProcessed runtime.Consumer[*types2.OrderProcessed]
}

type Service struct {
	runtime.ServiceApp
	makers                             serviceMakers
	functions                          serviceFunctions
	streams                            serviceStreams
	handlers                           serviceHandlers
	dataConnectors                     serviceDataConnectors
	httpServer                         *http.Server
	httpServerMaker                    func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMux                            *http.ServeMux
	httpMuxMaker                       func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)
	httpServerDone                     chan struct{}
	inventoryServiceApiGrpcClientMaker func(context.Context, *runtimecfg.GrpcDataConnectorConfig, runtime.RuntimeEnvironment) (*grpc.ClientConn, inventoryserviceapi.InventoryServiceApiClient, error)
	inventoryServiceApiGrpcClientConn  *grpc.ClientConn
	inventoryServiceApiGrpcClient      inventoryserviceapi.InventoryServiceApiClient
}

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	case runtimeserde.GetSerdeType[types.Order](), runtimeserde.GetSerdeType[*types.Order]():
		{
			var serde runtimeserde.Serde[*types.Order] = &serdes.OrderSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderItem](), runtimeserde.GetSerdeType[*types2.OrderItem]():
		{
			var serde runtimeserde.Serde[*types2.OrderItem] = &serdes2.OrderItemSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderItemResult](), runtimeserde.GetSerdeType[*types2.OrderItemResult]():
		{
			var serde runtimeserde.Serde[*types2.OrderItemResult] = &serdes2.OrderItemResultSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderProcessed](), runtimeserde.GetSerdeType[*types2.OrderProcessed]():
		{
			var serde runtimeserde.Serde[*types2.OrderProcessed] = &serdes2.OrderProcessedSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types.OrderState](), runtimeserde.GetSerdeType[*types.OrderState]():
		{
			var serde runtimeserde.Serde[*types.OrderState] = &serdes.OrderStateSerde{}
			return serde, nil
		}

	}
	return nil, nil
}

func (s *Service) RegisterHTTPHandler(path string, handler http.Handler) {
	if s.httpMux != nil {
		s.httpMux.Handle(path, s.httpHandlerMiddleware(path, handler))
	} else {
		s.ServiceApp.RegisterHTTPHandler(path, s.httpHandlerMiddleware(path, handler))
	}
}

func (s *Service) Config() *config.Config {
	return s.ServiceApp.GetConfig().(*config.Config)
}

func (s *Service) initMakers(ctx context.Context) error {
	s.httpMuxMaker = func(_ context.Context, _ runtime.RuntimeEnvironment) (*http.ServeMux, error) {
		return http.NewServeMux(), nil
	}
	if s.inventoryServiceApiGrpcClientMaker == nil {
		s.inventoryServiceApiGrpcClientMaker = func(ctx context.Context, cfg *runtimecfg.GrpcDataConnectorConfig, env runtime.RuntimeEnvironment) (*grpc.ClientConn, inventoryserviceapi.InventoryServiceApiClient, error) {
			connectionsCount := cfg.ConnectionsCount
			if connectionsCount == 0 {
				connectionsCount = 1
			}
			if connectionsCount < 1 {
				return nil, nil, fmt.Errorf("gRPC connector %q connectionsCount must be at least 1", cfg.Name)
			}
			opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}
			var statsHandlers []stats.Handler
			if me := env.MetricsEngine(); me != nil {
				if h := me.GRPCClientHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if te := env.TracingEngine(); te != nil {
				if h := te.GRPCClientHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if h := runtime.CombineGRPCStatsHandlers(statsHandlers...); h != nil {
				opts = append(opts, grpc.WithStatsHandler(h))
			}
			target := cfg.Address
			if connectionsCount > 1 {
				builder := manual.NewBuilderWithScheme(fmt.Sprintf("servicelib-%d", cfg.ID))
				address := strings.TrimPrefix(cfg.Address, "dns:///")
				address = strings.TrimPrefix(address, "passthrough:///")
				addresses := make([]resolver.Address, connectionsCount)
				for index := range addresses {
					addresses[index] = resolver.Address{
						Addr:       address,
						Attributes: attributes.New("servicelib.connection-index", index),
					}
				}
				builder.InitialState(resolver.State{Addresses: addresses})
				target = builder.Scheme() + ":///" + cfg.Name
				opts = append(
					opts,
					grpc.WithResolvers(builder),
					grpc.WithDefaultServiceConfig(`{"loadBalancingConfig":[{"round_robin":{}}]}`),
				)
			}
			conn, connErr := grpc.NewClient(target, opts...)
			if connErr != nil {
				return nil, nil, fmt.Errorf("gRPC client did not connect to server 'Inventory Service API': %w", connErr)
			}
			return conn, inventoryserviceapi.NewInventoryServiceApiClient(conn), nil
		}
	}
	if s.makers.orderProcessOrderItemsMaker == nil {
		s.makers.orderProcessOrderItemsMaker = func(ctx context.Context, cfg *runtimecfg.FlatMapStreamConfig, env environment.ServiceEnvironment) (*order.ProcessOrderItems, error) {
			return order.MakeProcessOrderItems(ctx, env, cfg)
		}
	}
	if s.makers.orderMapOrderItemResultToOrderStateMaker == nil {
		s.makers.orderMapOrderItemResultToOrderStateMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapOrderItemResultToOrderState, error) {
			return order.MakeMapOrderItemResultToOrderState(ctx, env, cfg)
		}
	}
	if s.makers.orderSoftDeadlineMaker == nil {
		s.makers.orderSoftDeadlineMaker = func(ctx context.Context, cfg *runtimecfg.DelayStreamConfig, env environment.ServiceEnvironment) (*order.SoftDeadline, error) {
			return order.MakeSoftDeadline(ctx, env, cfg)
		}
	}
	if s.makers.orderMapToOrderStateMaker == nil {
		s.makers.orderMapToOrderStateMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapToOrderState, error) {
			return order.MakeMapToOrderState(ctx, env, cfg)
		}
	}
	if s.makers.orderMapToOrderProcessedMaker == nil {
		s.makers.orderMapToOrderProcessedMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*order.MapToOrderProcessed, error) {
			return order.MakeMapToOrderProcessed(ctx, env, cfg)
		}
	}
	if s.makers.endpointProcessOrderSourceMaker == nil {
		s.makers.endpointProcessOrderSourceMaker = func(ctx context.Context, cfg *runtimecfg.HttpEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderSource, error) {
			return endpoint.MakeProcessOrderSource(ctx, env, cfg)
		}
	}
	if s.makers.endpointProcessOrderItemSinkMaker == nil {
		s.makers.endpointProcessOrderItemSinkMaker = func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSink, error) {
			return endpoint.MakeProcessOrderItemSink(ctx, env, cfg)
		}
	}
	if s.makers.endpointOrderProcessedEndpointSinkMaker == nil {
		s.makers.endpointOrderProcessedEndpointSinkMaker = func(ctx context.Context, cfg *runtimecfg.KafkaEndpointConfig, env environment.ServiceEnvironment) (*endpoint.OrderProcessedEndpointSink, error) {
			return endpoint.MakeOrderProcessedEndpointSink(ctx, env, cfg)
		}
	}

	return nil
}

func (s *Service) buildRuntime(ctx context.Context) error {
	cfg := s.Config()

	if err := s.initMakers(ctx); err != nil {
		return fmt.Errorf("init makers failed: %w", err)
	}

	if err := s.customMakersInit(ctx); err != nil {
		return fmt.Errorf("custom init makers failed: %w", err)
	}

	var err error

	if s.httpMuxMaker != nil {
		if s.httpMux, err = s.httpMuxMaker(ctx, s); err != nil {
			return fmt.Errorf("create http mux failed: %w", err)
		}
	}
	if err := s.initGrpcClients(ctx); err != nil {
		return fmt.Errorf("init gRPC clients failed: %w", err)
	}

	if err := s.initFunctions(ctx, cfg, s); err != nil {
		return fmt.Errorf("init functions failed: %w", err)
	}

	if err := s.customFunctionsInit(ctx); err != nil {
		return fmt.Errorf("custom functions init failed: %w", err)
	}

	if err := s.initStreams(ctx, cfg, s); err != nil {
		return fmt.Errorf("init streams failed: %w", err)
	}

	return nil
}

func (s *Service) initStreams(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	var err error
	if s.streams.processOrder, err = transformation.Input[*types.Order, *types.OrderState, error](&cfg.Streams.ProcessOrder, env); err != nil {
		return err
	}
	if s.streams.splitPipeline, err = transformation.Split[*types.Order](&cfg.Streams.SplitPipeline, s.streams.processOrder); err != nil {
		return err
	}
	if s.streams.processOrderItems, err = transformation.FlatMap[*types.Order, *types2.OrderItem](&cfg.Streams.ProcessOrderItems, s.streams.splitPipeline.AddStream(), s.functions.orderProcessOrderItems); err != nil {
		return err
	}
	if s.streams.processOrderItem, err = transformation.SinkWithResult[*types2.OrderItem, *types2.OrderItemResult, *types.OrderState](&cfg.Streams.ProcessOrderItem, s.streams.processOrderItems); err != nil {
		return err
	}
	s.streams.processOrderItemError = s.streams.processOrderItem.GetErrorStream()
	if s.streams.mapOrderItemResultToOrderState, err = transformation.Map[*types2.OrderItemResult, *types.OrderState](&cfg.Streams.MapOrderItemResultToOrderState, s.streams.processOrderItem, s.functions.orderMapOrderItemResultToOrderState); err != nil {
		return err
	}
	if s.streams.softDeadline, err = transformation.Delay[*types.Order](&cfg.Streams.SoftDeadline, s.streams.splitPipeline.AddStream(), s.functions.orderSoftDeadline); err != nil {
		return err
	}
	if s.streams.mapToOrderState, err = transformation.Map[*types.Order, *types.OrderState](&cfg.Streams.MapToOrderState, s.streams.softDeadline, s.functions.orderMapToOrderState); err != nil {
		return err
	}
	if s.streams.mergeResults, err = transformation.Merge[*types.OrderState](&cfg.Streams.MergeResults, s.streams.mapToOrderState, s.streams.mapOrderItemResultToOrderState, s.streams.processOrderItemError); err != nil {
		return err
	}
	if s.streams.splitOrderResult, err = transformation.Split[*types.OrderState](&cfg.Streams.SplitOrderResult, s.streams.mergeResults); err != nil {
		return err
	}
	if s.streams.mapToOrderProcessed, err = transformation.Map[*types.OrderState, *types2.OrderProcessed](&cfg.Streams.MapToOrderProcessed, s.streams.splitOrderResult.AddStream(), s.functions.orderMapToOrderProcessed); err != nil {
		return err
	}
	if s.streams.publishOrderProcessed, err = transformation.Sink[*types2.OrderProcessed, error](&cfg.Streams.PublishOrderProcessed, s.streams.mapToOrderProcessed); err != nil {
		return err
	}
	if err = s.streams.processOrder.SetSource(s.streams.splitOrderResult.AddStream()); err != nil {
		return err
	}
	if s.dataConnectors.processOrder, s.handlers.endpointProcessOrderSource, err = endpoint.MakeEndpointConsumerProcessOrderSource(s.streams.processOrder, s.functions.endpointProcessOrderSource); err != nil {
		return err
	}
	if s.dataConnectors.processOrderItemProcessOrderItem, err = endpoint.MakeEndpointConsumerProcessOrderItemSink(s.streams.processOrderItem, s.functions.endpointProcessOrderItemSink, func(ctx context.Context, req *processorderitem.ProcessOrderItemRequest) (*processorderitem.ProcessOrderItemResponse, error) {
		return s.inventoryServiceApiGrpcClient.ProcessOrderItem(ctx, req)
	}); err != nil {
		return err
	}
	if s.dataConnectors.publishOrderProcessedOrderProcessed, err = endpoint.MakeEndpointConsumerOrderProcessedEndpointSink(s.streams.publishOrderProcessed, s.functions.endpointOrderProcessedEndpointSink); err != nil {
		return err
	}
	_ = err
	_ = cfg
	return nil
}
func (s *Service) HasCustomHTTPServer() bool {
	return true
}

func (s *Service) initFunctions(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	eg, egCtx := errgroup.WithContext(ctx)
	if s.makers.orderProcessOrderItemsMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderProcessOrderItems, err = s.makers.orderProcessOrderItemsMaker(egCtx, &cfg.Streams.ProcessOrderItems, env)
			return err
		})
	}
	if s.makers.orderMapOrderItemResultToOrderStateMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderMapOrderItemResultToOrderState, err = s.makers.orderMapOrderItemResultToOrderStateMaker(egCtx, &cfg.Streams.MapOrderItemResultToOrderState, env)
			return err
		})
	}
	if s.makers.orderSoftDeadlineMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderSoftDeadline, err = s.makers.orderSoftDeadlineMaker(egCtx, &cfg.Streams.SoftDeadline, env)
			return err
		})
	}
	if s.makers.orderMapToOrderStateMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderMapToOrderState, err = s.makers.orderMapToOrderStateMaker(egCtx, &cfg.Streams.MapToOrderState, env)
			return err
		})
	}
	if s.makers.orderMapToOrderProcessedMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.orderMapToOrderProcessed, err = s.makers.orderMapToOrderProcessedMaker(egCtx, &cfg.Streams.MapToOrderProcessed, env)
			return err
		})
	}
	if s.makers.endpointProcessOrderSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointProcessOrderSource, err = s.makers.endpointProcessOrderSourceMaker(egCtx, &cfg.Endpoints.ProcessOrder, env)
			return err
		})
	}
	if s.makers.endpointProcessOrderItemSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointProcessOrderItemSink, err = s.makers.endpointProcessOrderItemSinkMaker(egCtx, &cfg.Endpoints.ProcessOrderItem, env)
			return err
		})
	}
	if s.makers.endpointOrderProcessedEndpointSinkMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointOrderProcessedEndpointSink, err = s.makers.endpointOrderProcessedEndpointSinkMaker(egCtx, &cfg.Endpoints.OrderProcessed, env)
			return err
		})
	}
	if err := eg.Wait(); err != nil {
		return err
	}
	return nil
}
func (s *Service) initGrpcClients(ctx context.Context) error {
	cfg := s.Config()
	eg, egCtx := errgroup.WithContext(ctx)
	eg.Go(func() error {
		conn, client, err := s.inventoryServiceApiGrpcClientMaker(egCtx, &cfg.DataConnectors.InventoryServiceApi, s)
		if err != nil {
			return fmt.Errorf("init gRPC client for 'Inventory Service API' failed: %w", err)
		}
		s.inventoryServiceApiGrpcClientConn = conn
		s.inventoryServiceApiGrpcClient = client
		return nil
	})
	return eg.Wait()
}

func (s *Service) ServiceInit() error {
	if s.httpMux == nil {
		s.httpMux = http.NewServeMux()
	}
	return nil
}

func (s *Service) StartService(ctx context.Context) error {

	if err := s.buildRuntime(ctx); err != nil {
		return fmt.Errorf("build runtime failed: %w", err)
	}

	if err := s.start(ctx); err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}

	if err := s.ServiceApp.Start(ctx); err != nil {
		return fmt.Errorf("service app start failed: %w", err)
	}

	var err error

	httpSvc := &HttpService{service: s}
	orderserviceapi.HandlerFromMux(httpSvc, s.httpMux)
	s.RegisterHTTPHandler("/swagger/orderserviceapi/", orderserviceapi.SwaggerHandler("/swagger/orderserviceapi/"))

	if s.httpMux != nil {
		if s.httpServerMaker != nil {
			if s.httpServer, err = s.httpServerMaker(ctx, s); err != nil {
				return fmt.Errorf("create http server failed: %w", err)
			}
		}
		if s.httpServer == nil {
			svcCfg := s.ServiceConfig()
			handler := http.Handler(s.httpMux)
			te := s.TracingEngine()
			if te != nil {
				handler = te.HTTPServerHandler(handler, runtime.ToSnakeCase(svcCfg.Name))
			}
			if me := s.MetricsEngine(); me != nil {
				handler = me.HTTPServerHandler(handler, runtime.ToSnakeCase(svcCfg.Name))
			}
			if te != nil {
				inner := handler
				handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
					if r.Header.Get("X-Trace") != "" {
						r = r.WithContext(tracing.EnableSampling(r.Context()))
					}
					inner.ServeHTTP(w, r)
				})
			}
			s.httpServer = &http.Server{
				Addr:    fmt.Sprintf("%s:%d", svcCfg.HttpHost, svcCfg.HttpPort),
				Handler: handler,
			}
		}
	}
	if s.httpServer != nil {
		s.httpServerDone = make(chan struct{})
		ln, err := net.Listen("tcp", s.httpServer.Addr)
		if err != nil {
			return fmt.Errorf("failed to listen http port: %v", err)
		}
		go func() {
			s.Log().Info(ctx, "HTTP server listening", log.Any("addr", s.httpServer.Addr))
			if err := s.httpServer.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
				s.Log().Error(ctx, "HTTP server stopped unexpectedly", log.Err(err))
			}
			close(s.httpServerDone)
		}()
	}
	return nil
}

func (s *Service) StopService(ctx context.Context) {
	svcCfg := s.ServiceConfig()
	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(svcCfg.ShutdownTimeout)*time.Millisecond)
	defer cancel()

	// First stop transport admission and let requests already accepted by the
	// HTTP/gRPC servers finish while the graph runtime and outbound clients
	// are still available to their handlers.
	wg := sync.WaitGroup{}
	admissionDone := make(chan struct{})
	if s.httpServer != nil {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := s.httpServer.Shutdown(timeoutCtx); err != nil {
				s.Log().Warn(timeoutCtx, "HTTP server shutdown", log.Err(err))
			}
			<-s.httpServerDone
		}()
	}
	go func() {
		wg.Wait()
		close(admissionDone)
	}()
	select {
	case <-admissionDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "transport drain timed out", log.Err(timeoutCtx.Err()))
	}

	// Only after inbound handlers have drained may graph resources, pools and
	// sinks stop. All phases share the same absolute shutdown deadline.
	runtimeDone := make(chan struct{})
	go func() {
		defer close(runtimeDone)
		s.ServiceApp.Stop(timeoutCtx)
	}()
	select {
	case <-runtimeDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "graph runtime stop timed out", log.Err(timeoutCtx.Err()))
	}

	// Outbound clients and user-owned resources are last: accepted handlers
	// and graph shutdown callbacks may still need them in earlier phases.
	cleanupWg := sync.WaitGroup{}

	cleanupWg.Add(1)
	go func() {
		defer cleanupWg.Done()
		if err := s.inventoryServiceApiGrpcClientConn.Close(); err != nil {
			s.Log().Warn(timeoutCtx, "gRPC client close error", log.Str("server", "Inventory Service API"), log.Err(err))
		}
	}()

	cleanupWg.Add(1)
	go func() {
		defer cleanupWg.Done()
		s.stop(timeoutCtx)
	}()
	cleanupDone := make(chan struct{})
	go func() {
		cleanupWg.Wait()
		close(cleanupDone)
	}()
	select {
	case <-cleanupDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "service cleanup timed out", log.Err(timeoutCtx.Err()))
	}
}

func Start(ctx context.Context,
	dependency environment.ServiceDependencies,
	done <-chan struct{},
	configPath *string,
	valuesPath *string,
	version string,
	commit string,
) error {
	if dependency == nil {
		dependency = &serviceDependencies{}
	}

	service, err := runtime.MakeService[*Service,
		*config.Config](
		ctx,
		"Order Service",
		dependency,
		configPath,
		valuesPath,
		func() *Service { return &Service{} },
		func() *config.Config { return config.MakeConfig() },
	)
	if err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}
	defer service.Release()

	service.Log().Info(ctx, "starting service", log.Str("service", service.ServiceConfig().Name), log.Str("version", version), log.Str("commit", commit))

	var stop chan os.Signal
	if done == nil {
		stop = make(chan os.Signal, 2)
		signal.Notify(stop, syscall.SIGINT)
		signal.Notify(stop, syscall.SIGTERM)
	}

	if ctx == nil {
		localCtx, cancel := context.WithCancel(context.Background())
		defer cancel()

		ctx = localCtx
	}

	if err = service.StartService(ctx); err != nil {
		return fmt.Errorf("start service failed: %w", err)
	}
	service.Log().Info(ctx, "service started", log.Str("service", service.ServiceConfig().Name))

	if os.Getenv("GORUNDEBUG_TEST") != "" && stop != nil {
		time.AfterFunc(1*time.Second, func() {
			close(stop)
		})
	}
	if stop != nil {
		<-stop
	} else if done != nil {
		<-done
	}
	service.Log().Info(ctx, "service stop signal received", log.Str("service", service.ServiceConfig().Name))
	service.StopService(context.WithoutCancel(ctx))
	service.Log().Info(ctx, "service stopped", log.Str("service", service.ServiceConfig().Name))
	return nil
}
