// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"errors"
	"fmt"
	"github.com/gorundebug/servicelib/runtime"
	log "github.com/gorundebug/servicelib/runtime/environment/log"
	"github.com/gorundebug/servicelib/runtime/environment/tracing"
	"net"
	"net/http"
	"sync"

	orderserviceapi "github.com/gorundebug/order_service_api/pkg/generated/openapi/orderserviceapi"
)

type serviceServers struct {
	httpServer     *http.Server
	httpMux        *http.ServeMux
	httpServerDone chan struct{}
}

func (s *Service) RegisterHTTPHandler(path string, handler http.Handler) {
	if s.servers.httpMux != nil {
		s.servers.httpMux.Handle(path, s.httpHandlerMiddleware(path, handler))
	} else {
		s.ServiceApp.RegisterHTTPHandler(path, s.httpHandlerMiddleware(path, handler))
	}
}

func (s *Service) ServiceInit() error {
	if s.servers.httpMux == nil {
		s.servers.httpMux = http.NewServeMux()
	}
	return nil
}
func (s *Service) HasCustomHTTPServer() bool {
	return true
}

func (servers *serviceServers) start(ctx context.Context, s *Service) error {
	var err error
	cfg := s.Config()

	if s.endpoints.handlers.processOrder != nil {
		s.RegisterHTTPHandler(cfg.Endpoints.ProcessOrder.Path, http.HandlerFunc(s.endpoints.handlers.processOrder))
	} else {
		return fmt.Errorf("http error handler is nil for endpoint %q", "Process Order")
	}
	httpSvc := &HttpService{service: s}
	orderserviceapi.HandlerFromMux(httpSvc, servers.httpMux)
	s.RegisterHTTPHandler("/swagger/orderserviceapi/", orderserviceapi.SwaggerHandler("/swagger/orderserviceapi/"))

	if servers.httpMux != nil {
		if s.makers.httpServerMaker != nil {
			if servers.httpServer, err = s.makers.httpServerMaker(ctx, s); err != nil {
				return fmt.Errorf("create http server failed: %w", err)
			}
		}
		if servers.httpServer == nil {
			svcCfg := s.ServiceConfig()
			handler := http.Handler(servers.httpMux)
			te := s.TracingEngine()
			if te != nil {
				handler = te.HTTPServerHandler(handler, runtime.ToSnakeCase(svcCfg.Name))
			}
			if me := s.MetricsEngine(); me != nil {
				handler = me.HTTPServerHandler(handler, runtime.ToSnakeCase(svcCfg.Name))
			}
			if te != nil && te.Tracing() != nil {
				inner := handler
				handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
					if r.Header.Get("X-Trace") != "" {
						r = r.WithContext(tracing.EnableSampling(r.Context()))
					}
					inner.ServeHTTP(w, r)
				})
			}
			servers.httpServer = &http.Server{
				Addr:    fmt.Sprintf("%s:%d", svcCfg.HttpHost, svcCfg.HttpPort),
				Handler: handler,
			}
		}
	}
	if servers.httpServer != nil {
		servers.httpServerDone = make(chan struct{})
		ln, err := net.Listen("tcp", servers.httpServer.Addr)
		if err != nil {
			return fmt.Errorf("failed to listen http port: %v", err)
		}
		go func() {
			s.Log().Info(ctx, "HTTP server listening", log.Any("addr", servers.httpServer.Addr))
			if err := servers.httpServer.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
				s.Log().Error(ctx, "HTTP server stopped unexpectedly", log.Err(err))
			}
			close(servers.httpServerDone)
		}()
	}
	return nil
}

func (servers *serviceServers) stop(timeoutCtx context.Context, s *Service) {
	// First stop transport admission and let requests already accepted by the
	// HTTP/gRPC servers finish while the graph runtime and outbound clients
	// are still available to their handlers.
	wg := sync.WaitGroup{}
	admissionDone := make(chan struct{})
	if servers.httpServer != nil {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := servers.httpServer.Shutdown(timeoutCtx); err != nil {
				s.Log().Warn(timeoutCtx, "HTTP server shutdown", log.Err(err))
			}
			<-servers.httpServerDone
		}()
	}
	go func() {
		wg.Wait()
		close(admissionDone)
	}()
	select {
	case <-admissionDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "transport drain timed out", log.Err(timeoutCtx.Err()))
	}

}
