// Code generated by servicegen. DO NOT EDIT.
package app

import (
	serdes2 "github.com/gorundebug/model_go/pkg/serdes"
	types2 "github.com/gorundebug/model_go/pkg/types"
	serdes "github.com/gorundebug/orderservice/internal/serdes"
	types "github.com/gorundebug/orderservice/internal/types"
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"
	"reflect"
)

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	case runtimeserde.GetSerdeType[types.Order](), runtimeserde.GetSerdeType[*types.Order]():
		{
			var serde runtimeserde.Serde[*types.Order] = &serdes.OrderSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderItem](), runtimeserde.GetSerdeType[*types2.OrderItem]():
		{
			var serde runtimeserde.Serde[*types2.OrderItem] = &serdes2.OrderItemSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderItemResult](), runtimeserde.GetSerdeType[*types2.OrderItemResult]():
		{
			var serde runtimeserde.Serde[*types2.OrderItemResult] = &serdes2.OrderItemResultSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderProcessed](), runtimeserde.GetSerdeType[*types2.OrderProcessed]():
		{
			var serde runtimeserde.Serde[*types2.OrderProcessed] = &serdes2.OrderProcessedSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types.OrderState](), runtimeserde.GetSerdeType[*types.OrderState]():
		{
			var serde runtimeserde.Serde[*types.OrderState] = &serdes.OrderStateSerde{}
			return serde, nil
		}

	}
	return nil, nil
}
