// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"reflect"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	log "github.com/gorundebug/servicelib/runtime/environment/log"
	"github.com/gorundebug/servicelib/runtime/environment/tracing"
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"
	"golang.org/x/sync/errgroup"
	"google.golang.org/grpc"
	"google.golang.org/grpc/attributes"
	_ "google.golang.org/grpc/balancer/roundrobin"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/resolver"
	"google.golang.org/grpc/resolver/manual"
	"google.golang.org/grpc/stats"

	"github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi"
	serdes2 "github.com/gorundebug/model_go/pkg/serdes"
	types2 "github.com/gorundebug/model_go/pkg/types"
	"github.com/gorundebug/order_service_api/pkg/generated/openapi/orderserviceapi"
	"github.com/gorundebug/orderservice/internal/config"
	"github.com/gorundebug/orderservice/internal/serdes"
	"github.com/gorundebug/orderservice/internal/types"
)

type serviceMakers struct {
	orderPipelineMakers
}

type serviceFunctions struct {
	orderPipelineFunctions
}

type serviceStreams struct {
	orderPipelineStreams
}

type serviceHandlers struct {
	orderPipelineHandlers
}

type serviceDataConnectors struct {
	orderPipelineDataConnectors
}

type Service struct {
	runtime.ServiceApp
	makers                             serviceMakers
	functions                          serviceFunctions
	streams                            serviceStreams
	handlers                           serviceHandlers
	dataConnectors                     serviceDataConnectors
	httpServer                         *http.Server
	httpServerMaker                    func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMux                            *http.ServeMux
	httpMuxMaker                       func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)
	httpServerDone                     chan struct{}
	inventoryServiceApiGrpcClientMaker func(context.Context, *runtimecfg.GrpcDataConnectorConfig, runtime.RuntimeEnvironment) (*grpc.ClientConn, inventoryserviceapi.InventoryServiceApiClient, error)
	inventoryServiceApiGrpcClientConn  *grpc.ClientConn
	inventoryServiceApiGrpcClient      inventoryserviceapi.InventoryServiceApiClient
}

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	case runtimeserde.GetSerdeType[types.Order](), runtimeserde.GetSerdeType[*types.Order]():
		{
			var serde runtimeserde.Serde[*types.Order] = &serdes.OrderSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderItem](), runtimeserde.GetSerdeType[*types2.OrderItem]():
		{
			var serde runtimeserde.Serde[*types2.OrderItem] = &serdes2.OrderItemSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderItemResult](), runtimeserde.GetSerdeType[*types2.OrderItemResult]():
		{
			var serde runtimeserde.Serde[*types2.OrderItemResult] = &serdes2.OrderItemResultSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types2.OrderProcessed](), runtimeserde.GetSerdeType[*types2.OrderProcessed]():
		{
			var serde runtimeserde.Serde[*types2.OrderProcessed] = &serdes2.OrderProcessedSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types.OrderState](), runtimeserde.GetSerdeType[*types.OrderState]():
		{
			var serde runtimeserde.Serde[*types.OrderState] = &serdes.OrderStateSerde{}
			return serde, nil
		}

	}
	return nil, nil
}

func (s *Service) RegisterHTTPHandler(path string, handler http.Handler) {
	if s.httpMux != nil {
		s.httpMux.Handle(path, s.httpHandlerMiddleware(path, handler))
	} else {
		s.ServiceApp.RegisterHTTPHandler(path, s.httpHandlerMiddleware(path, handler))
	}
}

func (s *Service) Config() *config.Config {
	return s.ServiceApp.GetConfig().(*config.Config)
}

func (s *Service) initMakers(ctx context.Context) error {
	s.httpMuxMaker = func(_ context.Context, _ runtime.RuntimeEnvironment) (*http.ServeMux, error) {
		return http.NewServeMux(), nil
	}
	if s.inventoryServiceApiGrpcClientMaker == nil {
		s.inventoryServiceApiGrpcClientMaker = func(ctx context.Context, cfg *runtimecfg.GrpcDataConnectorConfig, env runtime.RuntimeEnvironment) (*grpc.ClientConn, inventoryserviceapi.InventoryServiceApiClient, error) {
			connectionsCount := cfg.ConnectionsCount
			if connectionsCount == 0 {
				connectionsCount = 1
			}
			if connectionsCount < 1 {
				return nil, nil, fmt.Errorf("gRPC connector %q connectionsCount must be at least 1", cfg.Name)
			}
			opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}
			var statsHandlers []stats.Handler
			if me := env.MetricsEngine(); me != nil {
				if h := me.GRPCClientHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if te := env.TracingEngine(); te != nil {
				if h := te.GRPCClientHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if h := runtime.CombineGRPCStatsHandlers(statsHandlers...); h != nil {
				opts = append(opts, grpc.WithStatsHandler(h))
			}
			target := cfg.Address
			if connectionsCount > 1 {
				builder := manual.NewBuilderWithScheme(fmt.Sprintf("servicelib-%d", cfg.ID))
				address := strings.TrimPrefix(cfg.Address, "dns:///")
				address = strings.TrimPrefix(address, "passthrough:///")
				addresses := make([]resolver.Address, connectionsCount)
				for index := range addresses {
					addresses[index] = resolver.Address{
						Addr:       address,
						Attributes: attributes.New("servicelib.connection-index", index),
					}
				}
				builder.InitialState(resolver.State{Addresses: addresses})
				target = builder.Scheme() + ":///" + cfg.Name
				opts = append(
					opts,
					grpc.WithResolvers(builder),
					grpc.WithDefaultServiceConfig(`{"loadBalancingConfig":[{"round_robin":{}}]}`),
				)
			}
			conn, connErr := grpc.NewClient(target, opts...)
			if connErr != nil {
				return nil, nil, fmt.Errorf("gRPC client did not connect to server 'Inventory Service API': %w", connErr)
			}
			return conn, inventoryserviceapi.NewInventoryServiceApiClient(conn), nil
		}
	}
	s.initOrderMakers()

	return nil
}

func (s *Service) buildRuntime(ctx context.Context) error {
	cfg := s.Config()

	if err := s.initMakers(ctx); err != nil {
		return fmt.Errorf("init makers failed: %w", err)
	}

	if err := s.customMakersInit(ctx); err != nil {
		return fmt.Errorf("custom init makers failed: %w", err)
	}

	var err error

	if s.httpMuxMaker != nil {
		if s.httpMux, err = s.httpMuxMaker(ctx, s); err != nil {
			return fmt.Errorf("create http mux failed: %w", err)
		}
	}
	if err := s.initGrpcClients(ctx); err != nil {
		return fmt.Errorf("init gRPC clients failed: %w", err)
	}

	if err := s.initFunctions(ctx, cfg, s); err != nil {
		return fmt.Errorf("init functions failed: %w", err)
	}

	if err := s.customFunctionsInit(ctx); err != nil {
		return fmt.Errorf("custom functions init failed: %w", err)
	}

	if err := s.initStreams(ctx, cfg, s); err != nil {
		return fmt.Errorf("init streams failed: %w", err)
	}

	return nil
}

func (s *Service) initStreams(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	var err error
	if err = s.initOrderStreams(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.bindOrderStreams(); err != nil {
		return err
	}
	if err = s.initOrderEndpoints(); err != nil {
		return err
	}
	if err = s.postInitOrderStreams(); err != nil {
		return err
	}
	_ = err
	_ = cfg
	return nil
}
func (s *Service) HasCustomHTTPServer() bool {
	return true
}

type pipelineMakerTaskGroup interface {
	Go(func() error)
}

func (s *Service) initFunctions(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	eg, egCtx := errgroup.WithContext(ctx)
	s.scheduleOrderFunctions(eg, egCtx, cfg, env)
	if err := eg.Wait(); err != nil {
		return err
	}
	return nil
}
func (s *Service) initGrpcClients(ctx context.Context) error {
	cfg := s.Config()
	eg, egCtx := errgroup.WithContext(ctx)
	eg.Go(func() error {
		conn, client, err := s.inventoryServiceApiGrpcClientMaker(egCtx, &cfg.DataConnectors.InventoryServiceApi, s)
		if err != nil {
			return fmt.Errorf("init gRPC client for 'Inventory Service API' failed: %w", err)
		}
		s.inventoryServiceApiGrpcClientConn = conn
		s.inventoryServiceApiGrpcClient = client
		return nil
	})
	return eg.Wait()
}

func (s *Service) ServiceInit() error {
	if s.httpMux == nil {
		s.httpMux = http.NewServeMux()
	}
	return nil
}

func (s *Service) StartService(ctx context.Context) error {

	if err := s.buildRuntime(ctx); err != nil {
		return fmt.Errorf("build runtime failed: %w", err)
	}

	if err := s.start(ctx); err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}

	if err := s.ServiceApp.Start(ctx); err != nil {
		return fmt.Errorf("service app start failed: %w", err)
	}

	var err error

	httpSvc := &HttpService{service: s}
	orderserviceapi.HandlerFromMux(httpSvc, s.httpMux)
	s.RegisterHTTPHandler("/swagger/orderserviceapi/", orderserviceapi.SwaggerHandler("/swagger/orderserviceapi/"))

	if s.httpMux != nil {
		if s.httpServerMaker != nil {
			if s.httpServer, err = s.httpServerMaker(ctx, s); err != nil {
				return fmt.Errorf("create http server failed: %w", err)
			}
		}
		if s.httpServer == nil {
			svcCfg := s.ServiceConfig()
			handler := http.Handler(s.httpMux)
			te := s.TracingEngine()
			if te != nil {
				handler = te.HTTPServerHandler(handler, runtime.ToSnakeCase(svcCfg.Name))
			}
			if me := s.MetricsEngine(); me != nil {
				handler = me.HTTPServerHandler(handler, runtime.ToSnakeCase(svcCfg.Name))
			}
			if te != nil && te.Tracing() != nil {
				inner := handler
				handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
					if r.Header.Get("X-Trace") != "" {
						r = r.WithContext(tracing.EnableSampling(r.Context()))
					}
					inner.ServeHTTP(w, r)
				})
			}
			s.httpServer = &http.Server{
				Addr:    fmt.Sprintf("%s:%d", svcCfg.HttpHost, svcCfg.HttpPort),
				Handler: handler,
			}
		}
	}
	if s.httpServer != nil {
		s.httpServerDone = make(chan struct{})
		ln, err := net.Listen("tcp", s.httpServer.Addr)
		if err != nil {
			return fmt.Errorf("failed to listen http port: %v", err)
		}
		go func() {
			s.Log().Info(ctx, "HTTP server listening", log.Any("addr", s.httpServer.Addr))
			if err := s.httpServer.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
				s.Log().Error(ctx, "HTTP server stopped unexpectedly", log.Err(err))
			}
			close(s.httpServerDone)
		}()
	}
	return nil
}

func (s *Service) StopService(ctx context.Context) {
	svcCfg := s.ServiceConfig()
	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(svcCfg.ShutdownTimeout)*time.Millisecond)
	defer cancel()

	// First stop transport admission and let requests already accepted by the
	// HTTP/gRPC servers finish while the graph runtime and outbound clients
	// are still available to their handlers.
	wg := sync.WaitGroup{}
	admissionDone := make(chan struct{})
	if s.httpServer != nil {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := s.httpServer.Shutdown(timeoutCtx); err != nil {
				s.Log().Warn(timeoutCtx, "HTTP server shutdown", log.Err(err))
			}
			<-s.httpServerDone
		}()
	}
	go func() {
		wg.Wait()
		close(admissionDone)
	}()
	select {
	case <-admissionDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "transport drain timed out", log.Err(timeoutCtx.Err()))
	}

	// Only after inbound handlers have drained may graph resources, pools and
	// sinks stop. All phases share the same absolute shutdown deadline.
	runtimeDone := make(chan struct{})
	go func() {
		defer close(runtimeDone)
		s.ServiceApp.Stop(timeoutCtx)
	}()
	select {
	case <-runtimeDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "graph runtime stop timed out", log.Err(timeoutCtx.Err()))
	}

	// Outbound clients and user-owned resources are last: accepted handlers
	// and graph shutdown callbacks may still need them in earlier phases.
	cleanupWg := sync.WaitGroup{}

	cleanupWg.Add(1)
	go func() {
		defer cleanupWg.Done()
		if err := s.inventoryServiceApiGrpcClientConn.Close(); err != nil {
			s.Log().Warn(timeoutCtx, "gRPC client close error", log.Str("server", "Inventory Service API"), log.Err(err))
		}
	}()

	cleanupWg.Add(1)
	go func() {
		defer cleanupWg.Done()
		s.stop(timeoutCtx)
	}()
	cleanupDone := make(chan struct{})
	go func() {
		cleanupWg.Wait()
		close(cleanupDone)
	}()
	select {
	case <-cleanupDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "service cleanup timed out", log.Err(timeoutCtx.Err()))
	}
}

func Start(ctx context.Context,
	dependency environment.ServiceDependencies,
	done <-chan struct{},
	configPath *string,
	valuesPath *string,
	version string,
	commit string,
) error {
	if dependency == nil {
		dependency = &serviceDependencies{}
	}

	service, err := runtime.MakeService[*Service,
		*config.Config](
		ctx,
		"Order Service",
		dependency,
		configPath,
		valuesPath,
		func() *Service { return &Service{} },
		func() *config.Config { return config.MakeConfig() },
	)
	if err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}
	defer service.Release()

	service.Log().Info(ctx, "starting service", log.Str("service", service.ServiceConfig().Name), log.Str("version", version), log.Str("commit", commit))

	var stop chan os.Signal
	if done == nil {
		stop = make(chan os.Signal, 2)
		signal.Notify(stop, syscall.SIGINT)
		signal.Notify(stop, syscall.SIGTERM)
	}

	if ctx == nil {
		localCtx, cancel := context.WithCancel(context.Background())
		defer cancel()

		ctx = localCtx
	}

	if err = service.StartService(ctx); err != nil {
		return fmt.Errorf("start service failed: %w", err)
	}
	service.Log().Info(ctx, "service started", log.Str("service", service.ServiceConfig().Name))

	if os.Getenv("GORUNDEBUG_TEST") != "" && stop != nil {
		time.AfterFunc(1*time.Second, func() {
			close(stop)
		})
	}
	if stop != nil {
		<-stop
	} else if done != nil {
		<-done
	}
	service.Log().Info(ctx, "service stop signal received", log.Str("service", service.ServiceConfig().Name))
	service.StopService(context.WithoutCancel(ctx))
	service.Log().Info(ctx, "service stopped", log.Str("service", service.ServiceConfig().Name))
	return nil
}
