// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"github.com/gorundebug/servicelib/runtime"
	"github.com/gorundebug/servicelib/transformation"

	types2 "github.com/gorundebug/model_go/pkg/types"
	config "github.com/gorundebug/orderservice/internal/config"
	types "github.com/gorundebug/orderservice/internal/types"
)

type serviceStreams struct {
	processOrder                   runtime.TypedInputStream[*types.Order, *types.OrderState, error]
	splitPipeline                  runtime.TypedSplitStream[*types.Order]
	processOrderItems              runtime.TypedTransformConsumedStream[*types.Order, *types2.OrderItem]
	processOrderItem               runtime.TypedSinkStreamWithResult[*types2.OrderItem, *types2.OrderItemResult, *types.OrderState]
	processOrderItemError          runtime.TypedConsumedStream[*types.OrderState]
	mapOrderItemResultToOrderState runtime.TypedTransformConsumedStream[*types2.OrderItemResult, *types.OrderState]
	softDeadline                   runtime.TypedConsumedStream[*types.Order]
	mapToOrderState                runtime.TypedTransformConsumedStream[*types.Order, *types.OrderState]
	mergeResults                   runtime.TypedConsumedStream[*types.OrderState]
	splitOrderResult               runtime.TypedSplitStream[*types.OrderState]
	mapToOrderProcessed            runtime.TypedTransformConsumedStream[*types.OrderState, *types2.OrderProcessed]
	publishOrderProcessed          runtime.TypedSinkStream[*types2.OrderProcessed, error]
}

// initStreams preserves the global topological order, including cross-pipeline links.
func (streams *serviceStreams) initStreams(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment, functions *serviceFunctions) error {
	var err error

	if streams.processOrder, err = transformation.Input[*types.Order, *types.OrderState, error](&cfg.Streams.ProcessOrder, env); err != nil {
		return err
	}
	if streams.splitPipeline, err = transformation.Split[*types.Order](&cfg.Streams.SplitPipeline, streams.processOrder); err != nil {
		return err
	}
	if streams.processOrderItems, err = transformation.FlatMap[*types.Order, *types2.OrderItem](&cfg.Streams.ProcessOrderItems, streams.splitPipeline.AddStream(), functions.orderProcessOrderItems); err != nil {
		return err
	}
	if streams.processOrderItem, err = transformation.SinkWithResult[*types2.OrderItem, *types2.OrderItemResult, *types.OrderState](&cfg.Streams.ProcessOrderItem, streams.processOrderItems); err != nil {
		return err
	}
	streams.processOrderItemError = streams.processOrderItem.GetErrorStream()
	if streams.mapOrderItemResultToOrderState, err = transformation.Map[*types2.OrderItemResult, *types.OrderState](&cfg.Streams.MapOrderItemResultToOrderState, streams.processOrderItem, functions.orderMapOrderItemResultToOrderState); err != nil {
		return err
	}
	if streams.softDeadline, err = transformation.Delay[*types.Order](&cfg.Streams.SoftDeadline, streams.splitPipeline.AddStream(), functions.orderSoftDeadline); err != nil {
		return err
	}
	if streams.mapToOrderState, err = transformation.Map[*types.Order, *types.OrderState](&cfg.Streams.MapToOrderState, streams.softDeadline, functions.orderMapToOrderState); err != nil {
		return err
	}
	if streams.mergeResults, err = transformation.Merge[*types.OrderState](&cfg.Streams.MergeResults, streams.mapToOrderState, streams.mapOrderItemResultToOrderState, streams.processOrderItemError); err != nil {
		return err
	}
	if streams.splitOrderResult, err = transformation.Split[*types.OrderState](&cfg.Streams.SplitOrderResult, streams.mergeResults); err != nil {
		return err
	}
	if streams.mapToOrderProcessed, err = transformation.Map[*types.OrderState, *types2.OrderProcessed](&cfg.Streams.MapToOrderProcessed, streams.splitOrderResult.AddStream(), functions.orderMapToOrderProcessed); err != nil {
		return err
	}
	if streams.publishOrderProcessed, err = transformation.Sink[*types2.OrderProcessed, error](&cfg.Streams.PublishOrderProcessed, streams.mapToOrderProcessed); err != nil {
		return err
	}
	return err
}

// build binds result producers only after every stream has been constructed.
func (streams *serviceStreams) build() error {

	if err := streams.processOrder.SetSource(streams.splitOrderResult.AddStream()); err != nil {
		return err
	}

	return nil
}

// finish links cycles after endpoint consumers have been installed.
func (streams *serviceStreams) finish() error {
	var err error

	return err
}
