// Code generated by servicegen. DO NOT EDIT.
package config

import (
	"fmt"
	"os"
	"strconv"

	"github.com/gorundebug/servicelib/api"
	cfg "github.com/gorundebug/servicelib/runtime/config"
)

var _ = api.DataTypeAny

// Service IDs
const (
	orderServiceServiceID = iota + 1
)

// Stream IDs
const (
	mapOrderItemResultToOrderStateStreamID = iota + 1
	mapToOrderProcessedStreamID
	mapToOrderStateStreamID
	mergeResultsStreamID
	processOrderStreamID
	processOrderItemStreamID
	processOrderItemsStreamID
	publishOrderProcessedStreamID
	softDeadlineStreamID
	splitOrderResultStreamID
	splitPipelineStreamID
)

// Endpoint IDs
const (
	orderProcessedEndpointID = iota + 1
	processOrderEndpointID
	processOrderItemEndpointID
)

// Connector IDs
const (
	inventoryServiceApiConnectorID = iota + 1
	orderEventsConnectorID
	orderServiceApiConnectorID
)

type Config struct {
	Services struct {
		OrderService cfg.ServiceConfig `yaml:"orderService" mapstructure:"orderService"`
	} `yaml:"services" mapstructure:"services"`

	Streams struct {
		MapOrderItemResultToOrderState cfg.MapStreamConfig     `yaml:"mapOrderItemResultToOrderState" mapstructure:"mapOrderItemResultToOrderState"`
		MapToOrderProcessed            cfg.MapStreamConfig     `yaml:"mapToOrderProcessed" mapstructure:"mapToOrderProcessed"`
		MapToOrderState                cfg.MapStreamConfig     `yaml:"mapToOrderState" mapstructure:"mapToOrderState"`
		MergeResults                   cfg.MergeStreamConfig   `yaml:"mergeResults" mapstructure:"mergeResults"`
		ProcessOrder                   cfg.InputStreamConfig   `yaml:"processOrder" mapstructure:"processOrder"`
		ProcessOrderItem               cfg.SinkStreamConfig    `yaml:"processOrderItem" mapstructure:"processOrderItem"`
		ProcessOrderItems              cfg.FlatMapStreamConfig `yaml:"processOrderItems" mapstructure:"processOrderItems"`
		PublishOrderProcessed          cfg.SinkStreamConfig    `yaml:"publishOrderProcessed" mapstructure:"publishOrderProcessed"`
		SoftDeadline                   cfg.DelayStreamConfig   `yaml:"softDeadline" mapstructure:"softDeadline"`
		SplitOrderResult               cfg.SplitStreamConfig   `yaml:"splitOrderResult" mapstructure:"splitOrderResult"`
		SplitPipeline                  cfg.SplitStreamConfig   `yaml:"splitPipeline" mapstructure:"splitPipeline"`
	} `yaml:"streams" mapstructure:"streams"`

	DataConnectors struct {
		InventoryServiceApi cfg.GrpcDataConnectorConfig  `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		OrderEvents         cfg.KafkaDataConnectorConfig `yaml:"orderEvents" mapstructure:"orderEvents"`
		OrderServiceApi     cfg.HttpDataConnectorConfig  `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
	} `yaml:"dataConnectors" mapstructure:"dataConnectors"`

	Endpoints struct {
		OrderProcessed cfg.KafkaEndpointConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`

		ProcessOrder cfg.HttpEndpointConfig `yaml:"processOrder" mapstructure:"processOrder"`

		ProcessOrderItem cfg.GrpcEndpointConfig `yaml:"processOrderItem" mapstructure:"processOrderItem"`
	} `yaml:"endpoints" mapstructure:"endpoints"`

	Pools struct {
		DefaultPool cfg.PoolConfig `yaml:"defaultPool" mapstructure:"defaultPool"`
	} `yaml:"pools" mapstructure:"pools"`

	Links struct {
		MergeResultsToSplitOrderResult   cfg.LinkConfig `yaml:"mergeResultsToSplitOrderResult" mapstructure:"mergeResultsToSplitOrderResult"`
		ProcessOrderToSplitPipeline      cfg.LinkConfig `yaml:"processOrderToSplitPipeline" mapstructure:"processOrderToSplitPipeline"`
		SplitPipelineToProcessOrderItems cfg.LinkConfig `yaml:"splitPipelineToProcessOrderItems" mapstructure:"splitPipelineToProcessOrderItems"`
		SplitPipelineToSoftDeadline      cfg.LinkConfig `yaml:"splitPipelineToSoftDeadline" mapstructure:"splitPipelineToSoftDeadline"`
	} `yaml:"links" mapstructure:"links"`

	Modules struct {
		InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
		OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
	} `yaml:"modules" mapstructure:"modules"`

	Types struct {
		Order           cfg.TypeConfig `yaml:"order" mapstructure:"order"`
		OrderItem       cfg.TypeConfig `yaml:"orderItem" mapstructure:"orderItem"`
		OrderItemResult cfg.TypeConfig `yaml:"orderItemResult" mapstructure:"orderItemResult"`
		OrderProcessed  cfg.TypeConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`
		OrderState      cfg.TypeConfig `yaml:"orderState" mapstructure:"orderState"`
	} `yaml:"types" mapstructure:"types"`

	Custom     CustomConfig           `yaml:",inline" mapstructure:",squash"`
	Properties map[string]interface{} `yaml:",inline" mapstructure:",remain"`
}

func (c *Config) GetProperty(name string) interface{} {
	return c.Properties[name]
}

func (c *Config) GetServices() []*cfg.ServiceConfig {
	return []*cfg.ServiceConfig{
		&c.Services.OrderService,
	}
}

func (c *Config) GetStreams() []cfg.StreamConfig {
	return []cfg.StreamConfig{
		&c.Streams.MapOrderItemResultToOrderState,
		&c.Streams.MapToOrderProcessed,
		&c.Streams.MapToOrderState,
		&c.Streams.MergeResults,
		&c.Streams.ProcessOrder,
		&c.Streams.ProcessOrderItem,
		&c.Streams.ProcessOrderItems,
		&c.Streams.PublishOrderProcessed,
		&c.Streams.SoftDeadline,
		&c.Streams.SplitOrderResult,
		&c.Streams.SplitPipeline,
	}
}

func (c *Config) GetDataConnectors() []cfg.DataConnectorConfig {
	return []cfg.DataConnectorConfig{
		&c.DataConnectors.InventoryServiceApi,
		&c.DataConnectors.OrderEvents,
		&c.DataConnectors.OrderServiceApi,
	}
}

func (c *Config) GetEndpoints() []cfg.EndpointConfig {
	return []cfg.EndpointConfig{
		&c.Endpoints.OrderProcessed,
		&c.Endpoints.ProcessOrder,
		&c.Endpoints.ProcessOrderItem,
	}
}

func (c *Config) GetPools() []*cfg.PoolConfig {
	return []*cfg.PoolConfig{
		&c.Pools.DefaultPool,
	}
}

func (c *Config) GetLinks() []*cfg.LinkConfig {
	return []*cfg.LinkConfig{
		&c.Links.MergeResultsToSplitOrderResult,
		&c.Links.ProcessOrderToSplitPipeline,
		&c.Links.SplitPipelineToProcessOrderItems,
		&c.Links.SplitPipelineToSoftDeadline,
	}
}

func (c *Config) GetModules() []*cfg.ModuleConfig {
	return []*cfg.ModuleConfig{
		&c.Modules.InventoryServiceApi,
		&c.Modules.Model,
		&c.Modules.OrderServiceApi,
	}
}

func (c *Config) GetTypes() []*cfg.TypeConfig {
	return []*cfg.TypeConfig{
		&c.Types.Order,
		&c.Types.OrderItem,
		&c.Types.OrderItemResult,
		&c.Types.OrderProcessed,
		&c.Types.OrderState,
	}
}

func (c *Config) ApplyEnvironment() error {
	if err := c.applyDefaultPoolExecutorsCount(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceApiAddress(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceApiConnectionsCount(); err != nil {
		return err
	}
	if err := c.applyOrderEventsBrokers(); err != nil {
		return err
	}
	if err := c.applyOrderEventsPassword(); err != nil {
		return err
	}
	if err := c.applyOrderEventsSaslMechanism(); err != nil {
		return err
	}
	if err := c.applyOrderEventsSecurityProtocol(); err != nil {
		return err
	}
	if err := c.applyOrderEventsUsername(); err != nil {
		return err
	}
	if err := c.applyOrderProcessedEnabled(); err != nil {
		return err
	}
	if err := c.applyOrderServiceDefaultGrpcTimeout(); err != nil {
		return err
	}
	if err := c.applyOrderServiceEnvironment(); err != nil {
		return err
	}
	if err := c.applyOrderServiceGrpcHost(); err != nil {
		return err
	}
	if err := c.applyOrderServiceGrpcPort(); err != nil {
		return err
	}
	if err := c.applyOrderServiceHttpHost(); err != nil {
		return err
	}
	if err := c.applyOrderServiceHttpPort(); err != nil {
		return err
	}
	if err := c.applySoftDeadlineDuration(); err != nil {
		return err
	}
	return nil
}

func (c *Config) applyDefaultPoolExecutorsCount() error {
	value, exists := os.LookupEnv("DEFAULT_POOL_EXECUTORS_COUNT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert DEFAULT_POOL_EXECUTORS_COUNT to int: %w", err)
	}
	c.Pools.DefaultPool.ExecutorsCount = intVal

	return nil
}

func (c *Config) applyInventoryServiceApiAddress() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_API_ADDRESS")
	if !exists {
		return nil
	}

	c.DataConnectors.InventoryServiceApi.Address = value

	return nil
}

func (c *Config) applyInventoryServiceApiConnectionsCount() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_API_CONNECTIONS_COUNT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert INVENTORY_SERVICE_API_CONNECTIONS_COUNT to int: %w", err)
	}
	c.DataConnectors.InventoryServiceApi.ConnectionsCount = intVal

	return nil
}

func (c *Config) applyOrderEventsBrokers() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_BROKERS")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.Brokers = value

	return nil
}

func (c *Config) applyOrderEventsPassword() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_PASSWORD")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.Password = value

	return nil
}

func (c *Config) applyOrderEventsSaslMechanism() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_SASL_MECHANISM")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.SaslMechanism = api.KafkaSaslMechanism(value)

	return nil
}

func (c *Config) applyOrderEventsSecurityProtocol() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_SECURITY_PROTOCOL")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.SecurityProtocol = api.KafkaSecurityProtocol(value)

	return nil
}

func (c *Config) applyOrderEventsUsername() error {
	value, exists := os.LookupEnv("ORDER_EVENTS_USERNAME")
	if !exists {
		return nil
	}

	c.DataConnectors.OrderEvents.Username = value

	return nil
}

func (c *Config) applyOrderProcessedEnabled() error {
	value, exists := os.LookupEnv("ORDER_PROCESSED_ENABLED")
	if !exists {
		return nil
	}

	boolVal, err := strconv.ParseBool(value)
	if err != nil {
		return fmt.Errorf("failed to convert ORDER_PROCESSED_ENABLED to bool: %w", err)
	}
	c.Endpoints.OrderProcessed.Enabled = boolVal

	return nil
}

func (c *Config) applyOrderServiceDefaultGrpcTimeout() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_DEFAULT_GRPC_TIMEOUT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ORDER_SERVICE_DEFAULT_GRPC_TIMEOUT to int: %w", err)
	}
	c.Services.OrderService.DefaultGrpcTimeout = intVal

	return nil
}

func (c *Config) applyOrderServiceEnvironment() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_ENVIRONMENT")
	if !exists {
		return nil
	}

	c.Services.OrderService.Environment = api.Environment(value)

	return nil
}

func (c *Config) applyOrderServiceGrpcHost() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_GRPC_HOST")
	if !exists {
		return nil
	}

	c.Services.OrderService.GrpcHost = value

	return nil
}

func (c *Config) applyOrderServiceGrpcPort() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_GRPC_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ORDER_SERVICE_GRPC_PORT to int: %w", err)
	}
	c.Services.OrderService.GrpcPort = intVal

	return nil
}

func (c *Config) applyOrderServiceHttpHost() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_HTTP_HOST")
	if !exists {
		return nil
	}

	c.Services.OrderService.HttpHost = value

	return nil
}

func (c *Config) applyOrderServiceHttpPort() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_HTTP_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ORDER_SERVICE_HTTP_PORT to int: %w", err)
	}
	c.Services.OrderService.HttpPort = intVal

	return nil
}

func (c *Config) applySoftDeadlineDuration() error {
	value, exists := os.LookupEnv("SOFT_DEADLINE_DURATION")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert SOFT_DEADLINE_DURATION to int: %w", err)
	}
	c.Streams.SoftDeadline.Duration = intVal

	return nil
}

func MakeConfig() *Config {
	return &Config{
		Services: struct {
			OrderService cfg.ServiceConfig `yaml:"orderService" mapstructure:"orderService"`
		}{
			OrderService: cfg.ServiceConfig{
				ID:    orderServiceServiceID,
				Name:  "Order Service",
				Color: "#FF5C00",
				DefaultCallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
				GrpcHost:               "0.0.0.0",
				GrpcPort:               9201,
				HttpHost:               "0.0.0.0",
				HttpPort:               9091,
				MetricsHandler:         "metrics",
				StartupHandler:         "health/startup",
				ReadinessHandler:       "health/ready",
				LivenessHandler:        "health/live",
				KubernetesWorkloadType: "Deployment",
				ShutdownTimeout:        30000,
				StatusHandler:          "status",
				DefaultGrpcTimeout:     5000,
				GolangVersion:          "1.25.4",
				ModulePath:             "github.com/gorundebug/orderservice",
			},
		},
		Streams: struct {
			MapOrderItemResultToOrderState cfg.MapStreamConfig     `yaml:"mapOrderItemResultToOrderState" mapstructure:"mapOrderItemResultToOrderState"`
			MapToOrderProcessed            cfg.MapStreamConfig     `yaml:"mapToOrderProcessed" mapstructure:"mapToOrderProcessed"`
			MapToOrderState                cfg.MapStreamConfig     `yaml:"mapToOrderState" mapstructure:"mapToOrderState"`
			MergeResults                   cfg.MergeStreamConfig   `yaml:"mergeResults" mapstructure:"mergeResults"`
			ProcessOrder                   cfg.InputStreamConfig   `yaml:"processOrder" mapstructure:"processOrder"`
			ProcessOrderItem               cfg.SinkStreamConfig    `yaml:"processOrderItem" mapstructure:"processOrderItem"`
			ProcessOrderItems              cfg.FlatMapStreamConfig `yaml:"processOrderItems" mapstructure:"processOrderItems"`
			PublishOrderProcessed          cfg.SinkStreamConfig    `yaml:"publishOrderProcessed" mapstructure:"publishOrderProcessed"`
			SoftDeadline                   cfg.DelayStreamConfig   `yaml:"softDeadline" mapstructure:"softDeadline"`
			SplitOrderResult               cfg.SplitStreamConfig   `yaml:"splitOrderResult" mapstructure:"splitOrderResult"`
			SplitPipeline                  cfg.SplitStreamConfig   `yaml:"splitPipeline" mapstructure:"splitPipeline"`
		}{
			MapOrderItemResultToOrderState: cfg.MapStreamConfig{
				ID:                  mapOrderItemResultToOrderStateStreamID,
				Name:                "Map Order Item Result To Order State",
				Pipeline:            "order",
				IdService:           orderServiceServiceID,
				IdSource:            processOrderItemStreamID,
				XPos:                103,
				YPos:                -52,
				ValueType:           "OrderState",
				FunctionName:        "MapOrderItemResultToOrderState",
				FunctionDescription: "Produce an order result containing one inventory result and preserving its order ID.\nMark it CONFIRMED when the item was reserved; otherwise mark it PARTIALLY_CONFIRMED.\nRecord the time when this result is produced.\n",
			},

			MapToOrderProcessed: cfg.MapStreamConfig{
				ID:                  mapToOrderProcessedStreamID,
				Name:                "MapToOrderProcessed",
				Pipeline:            "order",
				IdService:           orderServiceServiceID,
				IdSource:            splitOrderResultStreamID,
				XPos:                -821,
				YPos:                -26,
				ValueType:           "OrderProcessed",
				FunctionName:        "MapToOrderProcessed",
				FunctionDescription: "Create an OrderProcessed event from the final order state.\nPreserve the order ID, status, and processing time. Count all item results and reserved items; for unsuccessful orders use the final status as the failure reason.\n",
			},

			MapToOrderState: cfg.MapStreamConfig{
				ID:                  mapToOrderStateStreamID,
				Name:                "Map to Order State",
				Pipeline:            "order",
				IdService:           orderServiceServiceID,
				IdSource:            softDeadlineStreamID,
				XPos:                -368,
				YPos:                -227,
				ValueType:           "OrderState",
				FunctionName:        "MapToOrderState",
				FunctionDescription: "Produce a TIMED_OUT order result that preserves the order ID and submitted total.\nDo not add item results at this stage; results received before the timeout are included in the final response.\n",
			},

			MergeResults: cfg.MergeStreamConfig{
				ID:        mergeResultsStreamID,
				Name:      "Merge Results",
				Pipeline:  "order",
				IdService: orderServiceServiceID,
				IdSources: []int{mapToOrderStateStreamID, mapOrderItemResultToOrderStateStreamID},
				XPos:      -228,
				YPos:      130,
			},

			ProcessOrder: cfg.InputStreamConfig{
				ID:         processOrderStreamID,
				Name:       "Process Order",
				Pipeline:   "order",
				IdService:  orderServiceServiceID,
				IdSource:   splitOrderResultStreamID,
				XPos:       -760,
				YPos:       -367,
				ValueType:  "Order",
				IdEndpoint: processOrderEndpointID,
			},

			ProcessOrderItem: cfg.SinkStreamConfig{
				ID:         processOrderItemStreamID,
				Name:       "Process Order Item",
				Pipeline:   "order",
				IdService:  orderServiceServiceID,
				IdSource:   processOrderItemsStreamID,
				XPos:       -60,
				YPos:       -375,
				ValueType:  "OrderItemResult",
				IdEndpoint: processOrderItemEndpointID,
			},

			ProcessOrderItems: cfg.FlatMapStreamConfig{
				ID:                  processOrderItemsStreamID,
				Name:                "Process Order Items",
				Pipeline:            "order",
				IdService:           orderServiceServiceID,
				IdSource:            splitPipelineStreamID,
				XPos:                -198,
				YPos:                -662,
				ValueType:           "OrderItem",
				FunctionName:        "ProcessOrderItems",
				FunctionDescription: "Emit every order item independently for inventory processing.\nPreserve each item's data and assign the parent order ID.\n",
			},

			PublishOrderProcessed: cfg.SinkStreamConfig{
				ID:         publishOrderProcessedStreamID,
				Name:       "Publish Order Processed",
				Pipeline:   "order",
				IdService:  orderServiceServiceID,
				IdSource:   mapToOrderProcessedStreamID,
				XPos:       -944,
				YPos:       -255,
				ValueType:  "OrderProcessed",
				IdEndpoint: orderProcessedEndpointID,
			},

			SoftDeadline: cfg.DelayStreamConfig{
				ID:                  softDeadlineStreamID,
				Name:                "Soft Deadline",
				Pipeline:            "order",
				IdService:           orderServiceServiceID,
				IdSource:            splitPipelineStreamID,
				XPos:                -477,
				YPos:                -444,
				Duration:            1000,
				FunctionName:        "SoftDeadline",
				FunctionDescription: "Trigger the timeout branch shortly before the request deadline, leaving the configured duration to assemble a response.\nWhen no request deadline exists, use the configured duration itself. Never wait past an existing deadline.\n",
			},

			SplitOrderResult: cfg.SplitStreamConfig{
				ID:        splitOrderResultStreamID,
				Name:      "Split Order Result",
				Pipeline:  "order",
				IdService: orderServiceServiceID,
				IdSource:  mergeResultsStreamID,
				XPos:      -671,
				YPos:      -129,
			},

			SplitPipeline: cfg.SplitStreamConfig{
				ID:        splitPipelineStreamID,
				Name:      "Split Pipeline",
				Pipeline:  "order",
				IdService: orderServiceServiceID,
				IdSource:  processOrderStreamID,
				XPos:      -640,
				YPos:      -597,
			},
		},
		DataConnectors: struct {
			InventoryServiceApi cfg.GrpcDataConnectorConfig  `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
			OrderEvents         cfg.KafkaDataConnectorConfig `yaml:"orderEvents" mapstructure:"orderEvents"`
			OrderServiceApi     cfg.HttpDataConnectorConfig  `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
		}{
			InventoryServiceApi: cfg.GrpcDataConnectorConfig{
				ID:               inventoryServiceApiConnectorID,
				Name:             "Inventory Service API",
				Implementation:   api.DataConnectorImplementationGoogleGRPC,
				Module:           "inventory_service_api",
				Address:          "dns:///localhost:9202",
				ConnectionsCount: 1,
			},

			OrderEvents: cfg.KafkaDataConnectorConfig{
				ID:               orderEventsConnectorID,
				Name:             "Order Events",
				Implementation:   api.DataConnectorImplementationIBMsarama,
				Brokers:          "redpanda:9092",
				Version:          "2.8.0",
				SecurityProtocol: "PLAINTEXT",
				SaslMechanism:    "SCRAM-SHA-512",
			},

			OrderServiceApi: cfg.HttpDataConnectorConfig{
				ID:             orderServiceApiConnectorID,
				Name:           "Order Service API",
				Implementation: api.DataConnectorImplementationNetHTTP,
				Module:         "order_service_api",
			},
		},
		Endpoints: struct {
			OrderProcessed   cfg.KafkaEndpointConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`
			ProcessOrder     cfg.HttpEndpointConfig  `yaml:"processOrder" mapstructure:"processOrder"`
			ProcessOrderItem cfg.GrpcEndpointConfig  `yaml:"processOrderItem" mapstructure:"processOrderItem"`
		}{
			OrderProcessed: cfg.KafkaEndpointConfig{
				ID:                  orderProcessedEndpointID,
				Name:                "Order Processed",
				IdDataConnector:     orderEventsConnectorID,
				Enabled:             true,
				CreateTopic:         true,
				Topic:               "order-processed",
				Partitions:          1,
				ReplicationFactor:   1,
				ConsumerGroup:       "analytics-service",
				FunctionName:        "OrderProcessedEndpoint",
				FunctionDescription: "Exchange OrderProcessed events keyed by order ID.\nProducers include the final status, processing time, total and confirmed item counts, and a failure reason for unsuccessful orders.\nConsumers decode the event and mark its Kafka message processed only after the pipeline handles it successfully.\n",
			},

			ProcessOrder: cfg.HttpEndpointConfig{
				ID:                  processOrderEndpointID,
				Name:                "Process Order",
				IdDataConnector:     orderServiceApiConnectorID,
				HttpMethodType:      api.HTTPMethodTypePOST,
				Path:                "/v1/processorder",
				FunctionName:        "ProcessOrder",
				FunctionDescription: "Accept orders with at least one item and positive quantities; reject malformed or invalid requests as client errors.\nReuse X-Request-ID when supplied, otherwise generate an order ID. Preserve customer, item, price, and X-Trace data, and apply the configured timeout of five seconds by default.\nReturn one response per order. When all items finish, use CONFIRMED only if every item was reserved; otherwise use PARTIALLY_CONFIRMED. If the deadline wins, return TIMED_OUT with the item results received so far.\nCalculate the total from processed item prices, falling back to the submitted total when no item result arrived, and include individual item failures in the response.\n",
			},

			ProcessOrderItem: cfg.GrpcEndpointConfig{
				ID:                  processOrderItemEndpointID,
				Name:                "Process Order Item",
				IdDataConnector:     inventoryServiceApiConnectorID,
				GrpcMethodType:      api.GrpcMethodTypeNoStreaming,
				MethodName:          "ProcessOrderItem",
				FunctionName:        "ProcessOrderItem",
				FunctionDescription: "Reserve inventory for one order item using its order ID, item ID, SKU, and quantity.\nReturn the available quantity, reservation outcome, and status. The caller combines this response with the original identity, requested quantity, and unit price.\nIf the inventory call fails, the caller returns a non-reserved PROCESSING_ERROR result with the failure message.\n",
			},
		},
		Pools: struct {
			DefaultPool cfg.PoolConfig `yaml:"defaultPool" mapstructure:"defaultPool"`
		}{
			DefaultPool: cfg.PoolConfig{
				Name:           "Default Pool",
				ExecutorsCount: 2,
			},
		},
		Links: struct {
			MergeResultsToSplitOrderResult   cfg.LinkConfig `yaml:"mergeResultsToSplitOrderResult" mapstructure:"mergeResultsToSplitOrderResult"`
			ProcessOrderToSplitPipeline      cfg.LinkConfig `yaml:"processOrderToSplitPipeline" mapstructure:"processOrderToSplitPipeline"`
			SplitPipelineToProcessOrderItems cfg.LinkConfig `yaml:"splitPipelineToProcessOrderItems" mapstructure:"splitPipelineToProcessOrderItems"`
			SplitPipelineToSoftDeadline      cfg.LinkConfig `yaml:"splitPipelineToSoftDeadline" mapstructure:"splitPipelineToSoftDeadline"`
		}{
			MergeResultsToSplitOrderResult: cfg.LinkConfig{
				From: mergeResultsStreamID,
				To:   splitOrderResultStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			ProcessOrderToSplitPipeline: cfg.LinkConfig{
				From: processOrderStreamID,
				To:   splitPipelineStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			SplitPipelineToProcessOrderItems: cfg.LinkConfig{
				From: splitPipelineStreamID,
				To:   processOrderItemsStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
			},
			SplitPipelineToSoftDeadline: cfg.LinkConfig{
				From: splitPipelineStreamID,
				To:   softDeadlineStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{
						Async: true,
					},
				},
			},
		},
		Modules: struct {
			InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
			Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
			OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
		}{
			InventoryServiceApi: cfg.ModuleConfig{
				Name: "inventory_service_api",
				Path: "github.com/gorundebug/inventory_service_api",
			},
			Model: cfg.ModuleConfig{
				Name: "model",
				Path: "github.com/gorundebug/model",
			},
			OrderServiceApi: cfg.ModuleConfig{
				Name: "order_service_api",
				Path: "github.com/gorundebug/order_service_api",
			},
		},
		Types: struct {
			Order           cfg.TypeConfig `yaml:"order" mapstructure:"order"`
			OrderItem       cfg.TypeConfig `yaml:"orderItem" mapstructure:"orderItem"`
			OrderItemResult cfg.TypeConfig `yaml:"orderItemResult" mapstructure:"orderItemResult"`
			OrderProcessed  cfg.TypeConfig `yaml:"orderProcessed" mapstructure:"orderProcessed"`
			OrderState      cfg.TypeConfig `yaml:"orderState" mapstructure:"orderState"`
		}{
			Order: cfg.TypeConfig{
				Name:             "Order",
				Type:             api.DataTypeStruct,
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			OrderItem: cfg.TypeConfig{
				Name:             "OrderItem",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			OrderItemResult: cfg.TypeConfig{
				Name:             "OrderItemResult",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			OrderProcessed: cfg.TypeConfig{
				Name:             "OrderProcessed",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			OrderState: cfg.TypeConfig{
				Name:             "OrderState",
				Type:             api.DataTypeStruct,
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},
		},
	}
}
