// Code generated by servicegen. DO NOT EDIT.
package config

import (
	"fmt"
	"os"
	"strconv"

	"github.com/gorundebug/servicelib/api"
	cfg "github.com/gorundebug/servicelib/runtime/config"
)

var _ = api.DataTypeAny

// Service IDs
const (
	orderServiceServiceID = iota + 1
)

// Stream IDs
const (
	mapOrderItemResultToOrderStateStreamID = iota + 1
	mapToOrderStateStreamID
	mergeResultsStreamID
	processOrderStreamID
	processOrderItemStreamID
	processOrderItemsStreamID
	softDeadlineStreamID
	splitPipelineStreamID
)

// Endpoint IDs
const (
	processOrderEndpointID = iota + 1
	processOrderItemEndpointID
)

// Connector IDs
const (
	inventoryServiceApiConnectorID = iota + 1
	orderServiceApiConnectorID
)

type Config struct {
	Services struct {
		OrderService cfg.ServiceConfig `yaml:"orderService" mapstructure:"orderService"`
	} `yaml:"services" mapstructure:"services"`

	Streams struct {
		MapOrderItemResultToOrderState cfg.MapStreamConfig     `yaml:"mapOrderItemResultToOrderState" mapstructure:"mapOrderItemResultToOrderState"`
		MapToOrderState                cfg.MapStreamConfig     `yaml:"mapToOrderState" mapstructure:"mapToOrderState"`
		MergeResults                   cfg.MergeStreamConfig   `yaml:"mergeResults" mapstructure:"mergeResults"`
		ProcessOrder                   cfg.InputStreamConfig   `yaml:"processOrder" mapstructure:"processOrder"`
		ProcessOrderItem               cfg.SinkStreamConfig    `yaml:"processOrderItem" mapstructure:"processOrderItem"`
		ProcessOrderItems              cfg.FlatMapStreamConfig `yaml:"processOrderItems" mapstructure:"processOrderItems"`
		SoftDeadline                   cfg.DelayStreamConfig   `yaml:"softDeadline" mapstructure:"softDeadline"`
		SplitPipeline                  cfg.SplitStreamConfig   `yaml:"splitPipeline" mapstructure:"splitPipeline"`
	} `yaml:"streams" mapstructure:"streams"`

	DataConnectors struct {
		InventoryServiceApi cfg.GrpcDataConnectorConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		OrderServiceApi     cfg.HttpDataConnectorConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
	} `yaml:"dataConnectors" mapstructure:"dataConnectors"`

	Endpoints struct {
		ProcessOrder cfg.HttpEndpointConfig `yaml:"processOrder" mapstructure:"processOrder"`

		ProcessOrderItem cfg.GrpcEndpointConfig `yaml:"processOrderItem" mapstructure:"processOrderItem"`
	} `yaml:"endpoints" mapstructure:"endpoints"`

	Pools struct {
	} `yaml:"pools" mapstructure:"pools"`

	Links struct {
	} `yaml:"links" mapstructure:"links"`

	Modules struct {
		InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
		OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
	} `yaml:"modules" mapstructure:"modules"`

	Types struct {
		Order           cfg.TypeConfig `yaml:"order" mapstructure:"order"`
		OrderItem       cfg.TypeConfig `yaml:"orderItem" mapstructure:"orderItem"`
		OrderItemResult cfg.TypeConfig `yaml:"orderItemResult" mapstructure:"orderItemResult"`
		OrderState      cfg.TypeConfig `yaml:"orderState" mapstructure:"orderState"`
	} `yaml:"types" mapstructure:"types"`

	Custom     CustomConfig           `yaml:",inline" mapstructure:",squash"`
	Properties map[string]interface{} `yaml:",inline" mapstructure:",remain"`
}

func (c *Config) GetProperty(name string) interface{} {
	return c.Properties[name]
}

func (c *Config) GetServices() []*cfg.ServiceConfig {
	return []*cfg.ServiceConfig{
		&c.Services.OrderService,
	}
}

func (c *Config) GetStreams() []cfg.StreamConfig {
	return []cfg.StreamConfig{
		&c.Streams.MapOrderItemResultToOrderState,
		&c.Streams.MapToOrderState,
		&c.Streams.MergeResults,
		&c.Streams.ProcessOrder,
		&c.Streams.ProcessOrderItem,
		&c.Streams.ProcessOrderItems,
		&c.Streams.SoftDeadline,
		&c.Streams.SplitPipeline,
	}
}

func (c *Config) GetDataConnectors() []cfg.DataConnectorConfig {
	return []cfg.DataConnectorConfig{
		&c.DataConnectors.InventoryServiceApi,
		&c.DataConnectors.OrderServiceApi,
	}
}

func (c *Config) GetEndpoints() []cfg.EndpointConfig {
	return []cfg.EndpointConfig{
		&c.Endpoints.ProcessOrder,
		&c.Endpoints.ProcessOrderItem,
	}
}

func (c *Config) GetPools() []*cfg.PoolConfig {
	return []*cfg.PoolConfig{}
}

func (c *Config) GetLinks() []*cfg.LinkConfig {
	return []*cfg.LinkConfig{}
}

func (c *Config) GetModules() []*cfg.ModuleConfig {
	return []*cfg.ModuleConfig{
		&c.Modules.InventoryServiceApi,
		&c.Modules.Model,
		&c.Modules.OrderServiceApi,
	}
}

func (c *Config) GetTypes() []*cfg.TypeConfig {
	return []*cfg.TypeConfig{
		&c.Types.Order,
		&c.Types.OrderItem,
		&c.Types.OrderItemResult,
		&c.Types.OrderState,
	}
}

func (c *Config) ApplyEnvironment() error {
	if err := c.applyInventoryServiceApiAddress(); err != nil {
		return err
	}
	if err := c.applyOrderServiceEnvironment(); err != nil {
		return err
	}
	if err := c.applyOrderServiceGrpcHost(); err != nil {
		return err
	}
	if err := c.applyOrderServiceGrpcPort(); err != nil {
		return err
	}
	if err := c.applyOrderServiceHttpHost(); err != nil {
		return err
	}
	if err := c.applyOrderServiceHttpPort(); err != nil {
		return err
	}
	return nil
}

func (c *Config) applyInventoryServiceApiAddress() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_API_ADDRESS")
	if !exists {
		return nil
	}

	c.DataConnectors.InventoryServiceApi.Address = value

	return nil
}

func (c *Config) applyOrderServiceEnvironment() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_ENVIRONMENT")
	if !exists {
		return nil
	}

	c.Services.OrderService.Environment = api.Environment(value)

	return nil
}

func (c *Config) applyOrderServiceGrpcHost() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_GRPC_HOST")
	if !exists {
		return nil
	}

	c.Services.OrderService.GrpcHost = value

	return nil
}

func (c *Config) applyOrderServiceGrpcPort() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_GRPC_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ORDER_SERVICE_GRPC_PORT to int: %w", err)
	}
	c.Services.OrderService.GrpcPort = intVal

	return nil
}

func (c *Config) applyOrderServiceHttpHost() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_HTTP_HOST")
	if !exists {
		return nil
	}

	c.Services.OrderService.HttpHost = value

	return nil
}

func (c *Config) applyOrderServiceHttpPort() error {
	value, exists := os.LookupEnv("ORDER_SERVICE_HTTP_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert ORDER_SERVICE_HTTP_PORT to int: %w", err)
	}
	c.Services.OrderService.HttpPort = intVal

	return nil
}

func MakeConfig() *Config {
	return &Config{
		Services: struct {
			OrderService cfg.ServiceConfig `yaml:"orderService" mapstructure:"orderService"`
		}{
			OrderService: cfg.ServiceConfig{
				ID:    orderServiceServiceID,
				Name:  "Order Service",
				Color: "#D2E5FF",
				DefaultCallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
				GrpcHost:        "0.0.0.0",
				GrpcPort:        9201,
				HttpHost:        "0.0.0.0",
				HttpPort:        9091,
				MetricsHandler:  "metrics",
				ShutdownTimeout: 30000,
				StatusHandler:   "status",
				GolangVersion:   "1.25.4",
				ModulePath:      "github.com/gorundebug/orderservice",
			},
		},
		Streams: struct {
			MapOrderItemResultToOrderState cfg.MapStreamConfig     `yaml:"mapOrderItemResultToOrderState" mapstructure:"mapOrderItemResultToOrderState"`
			MapToOrderState                cfg.MapStreamConfig     `yaml:"mapToOrderState" mapstructure:"mapToOrderState"`
			MergeResults                   cfg.MergeStreamConfig   `yaml:"mergeResults" mapstructure:"mergeResults"`
			ProcessOrder                   cfg.InputStreamConfig   `yaml:"processOrder" mapstructure:"processOrder"`
			ProcessOrderItem               cfg.SinkStreamConfig    `yaml:"processOrderItem" mapstructure:"processOrderItem"`
			ProcessOrderItems              cfg.FlatMapStreamConfig `yaml:"processOrderItems" mapstructure:"processOrderItems"`
			SoftDeadline                   cfg.DelayStreamConfig   `yaml:"softDeadline" mapstructure:"softDeadline"`
			SplitPipeline                  cfg.SplitStreamConfig   `yaml:"splitPipeline" mapstructure:"splitPipeline"`
		}{
			MapOrderItemResultToOrderState: cfg.MapStreamConfig{
				ID:                  mapOrderItemResultToOrderStateStreamID,
				Name:                "Map Order Item Result To Order State",
				Pipeline:            "order",
				IdService:           orderServiceServiceID,
				IdSource:            processOrderItemStreamID,
				XPos:                0,
				YPos:                0,
				ValueType:           "OrderState",
				FunctionName:        "MapOrderItemResultToOrderState",
				FunctionDescription: "Convert a single OrderItemResult into an OrderState.\nSet OrderID from result.OrderID; set Status=CONFIRMED if result.Reserved==true, otherwise PARTIALLY_CONFIRMED.\nSet ConfirmedItems to a single-element slice containing result.\n",
			},

			MapToOrderState: cfg.MapStreamConfig{
				ID:                  mapToOrderStateStreamID,
				Name:                "Map to Order State",
				Pipeline:            "order",
				IdService:           orderServiceServiceID,
				IdSource:            softDeadlineStreamID,
				XPos:                -459,
				YPos:                76,
				ValueType:           "OrderState",
				FunctionName:        "MapToOrderState",
				FunctionDescription: "Convert an Order that reached the soft deadline into an OrderState.\nSet OrderID from Order.ID; set Status to TIMED_OUT; leave ConfirmedItems nil.\n",
			},

			MergeResults: cfg.MergeStreamConfig{
				ID:        mergeResultsStreamID,
				Name:      "Merge Results",
				Pipeline:  "order",
				IdService: orderServiceServiceID,
				IdSources: []int{mapToOrderStateStreamID, mapOrderItemResultToOrderStateStreamID},
				XPos:      -178,
				YPos:      24,
			},

			ProcessOrder: cfg.InputStreamConfig{
				ID:         processOrderStreamID,
				Name:       "Process Order",
				Pipeline:   "order",
				IdService:  orderServiceServiceID,
				IdSource:   mergeResultsStreamID,
				XPos:       -343,
				YPos:       -229,
				ValueType:  "Order",
				IdEndpoint: processOrderEndpointID,
			},

			ProcessOrderItem: cfg.SinkStreamConfig{
				ID:         processOrderItemStreamID,
				Name:       "Process Order Item",
				Pipeline:   "order",
				IdService:  orderServiceServiceID,
				IdSource:   processOrderItemsStreamID,
				XPos:       -75,
				YPos:       -311,
				ValueType:  "OrderItemResult",
				IdEndpoint: processOrderItemEndpointID,
			},

			ProcessOrderItems: cfg.FlatMapStreamConfig{
				ID:                  processOrderItemsStreamID,
				Name:                "Process Order Items",
				Pipeline:            "order",
				IdService:           orderServiceServiceID,
				IdSource:            splitPipelineStreamID,
				XPos:                -197,
				YPos:                -473,
				ValueType:           "OrderItem",
				FunctionName:        "ProcessOrderItems",
				FunctionDescription: "Expand an Order into individual OrderItem messages — one sc.Collect call per element of Order.Items.\nCopy Order.ID into each emitted OrderItem.OrderID.\n",
			},

			SoftDeadline: cfg.DelayStreamConfig{
				ID:                  softDeadlineStreamID,
				Name:                "Soft Deadline",
				Pipeline:            "order",
				IdService:           orderServiceServiceID,
				IdSource:            splitPipelineStreamID,
				XPos:                -706,
				YPos:                -33,
				FunctionName:        "SoftDeadline",
				FunctionDescription: "Cast stream.GetConfig() to *runtimecfg.DelayStreamConfig and convert cfg.Duration (int, milliseconds) to time.Duration — this is the safety margin.\nIf ctx has no deadline (ctx.Deadline() ok==false), return the margin directly.\nOtherwise compute time.Until(deadline) minus the margin: if the result is negative return 0, otherwise return it.\n",
			},

			SplitPipeline: cfg.SplitStreamConfig{
				ID:        splitPipelineStreamID,
				Name:      "Split Pipeline",
				Pipeline:  "order",
				IdService: orderServiceServiceID,
				IdSource:  processOrderStreamID,
				XPos:      -416,
				YPos:      -472,
			},
		},
		DataConnectors: struct {
			InventoryServiceApi cfg.GrpcDataConnectorConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
			OrderServiceApi     cfg.HttpDataConnectorConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
		}{
			InventoryServiceApi: cfg.GrpcDataConnectorConfig{
				ID:             inventoryServiceApiConnectorID,
				Name:           "Inventory Service API",
				Implementation: api.DataConnectorImplementationGoogleGRPC,
				Module:         "inventory_service_api",
				Address:        "dns:///localhost:9202",
			},

			OrderServiceApi: cfg.HttpDataConnectorConfig{
				ID:             orderServiceApiConnectorID,
				Name:           "Order Service API",
				Implementation: api.DataConnectorImplementationNetHTTP,
				Module:         "order_service_api",
			},
		},
		Endpoints: struct {
			ProcessOrder     cfg.HttpEndpointConfig `yaml:"processOrder" mapstructure:"processOrder"`
			ProcessOrderItem cfg.GrpcEndpointConfig `yaml:"processOrderItem" mapstructure:"processOrderItem"`
		}{
			ProcessOrder: cfg.HttpEndpointConfig{
				ID:                  processOrderEndpointID,
				Name:                "Process Order",
				IdDataConnector:     orderServiceApiConnectorID,
				HttpMethodType:      api.HTTPMethodTypePOST,
				Path:                "/v1/processorder",
				FunctionName:        "ProcessOrder",
				FunctionDescription: "HTTP source handler for POST /v1/processorder.\n[Handler] holds timeout time.Duration read from config property 'timeout' (milliseconds, default 5000).\n[HandlerState] carries a context cancel function.\n[BeginRequest] attaches context timeout via WithTimeout, stores cancel in handler state.\n[ConsumeMessage] decodes JSON body; validates Items non-empty and all quantities positive (write 400 and return error on failure);\ngenerates order ID as UUID; maps each item to OrderItem (ItemId, SKU, Quantity);\nreads optional CustomerId; builds Order with CreatedAt=now;\nregisters result callback keyed on order ID; emits Order via sc.Collect.\n[Result callback] called once per result (N inventory results + possibly one TIMED_OUT);\ncaptures in its closure: sync.Mutex mu, accumulator []OrderItemResult, responseSent bool;\nlocks mu on each invocation;\nif responseSent return true;\nif Status==TIMED_OUT compute TotalAmount as sum of item.UnitPrice*item.RequestedQty for each accumulated item, write partial response with accumulated items, call Done(), return true;\notherwise append result.ConfirmedItems to accumulator and return false if len(accumulated) < N;\nwhen all N collected compute status (CONFIRMED if all items in accumulator have Reserved==true, else PARTIALLY_CONFIRMED),\ncompute TotalAmount as sum of item.UnitPrice * item.RequestedQty for each item in accumulator,\nwrite JSON response, call Done(), return true.\n[GetMessageID] returns OrderState.OrderID.\n[EndRequest] cancels context.\n[Private helper] converts OrderState to ProcessOrderResponse mapping all fields including optional ConfirmedItems slice.\n",
			},

			ProcessOrderItem: cfg.GrpcEndpointConfig{
				ID:                  processOrderItemEndpointID,
				Name:                "Process Order Item",
				IdDataConnector:     inventoryServiceApiConnectorID,
				GrpcMethodType:      api.GrpcMethodTypeNoStreaming,
				MethodName:          "ProcessOrderItem",
				FunctionName:        "ProcessOrderItem",
				FunctionDescription: "Outgoing unary gRPC call to the Inventory Service.\n[ConsumeMessage] map OrderItem → ProcessOrderItemRequest (OrderID, ItemID, SKU, Quantity); call sender.Send(req).\n[HandleResponse] map ProcessOrderItemResponse → OrderItemResult:\ncopy OrderID, ItemID, AvailableQty, Reserved, Status, UnitPrice from response; push downstream via sc.Collect.\n[EndRequest] log the outcome.\n",
			},
		},
		Pools: struct {
		}{},
		Links: struct {
		}{},
		Modules: struct {
			InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
			Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
			OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
		}{
			InventoryServiceApi: cfg.ModuleConfig{
				Name: "inventory_service_api",
				Path: "github.com/gorundebug/inventory_service_api",
			},
			Model: cfg.ModuleConfig{
				Name: "model",
				Path: "github.com/gorundebug/model",
			},
			OrderServiceApi: cfg.ModuleConfig{
				Name: "order_service_api",
				Path: "github.com/gorundebug/order_service_api",
			},
		},
		Types: struct {
			Order           cfg.TypeConfig `yaml:"order" mapstructure:"order"`
			OrderItem       cfg.TypeConfig `yaml:"orderItem" mapstructure:"orderItem"`
			OrderItemResult cfg.TypeConfig `yaml:"orderItemResult" mapstructure:"orderItemResult"`
			OrderState      cfg.TypeConfig `yaml:"orderState" mapstructure:"orderState"`
		}{
			Order: cfg.TypeConfig{
				Name:             "Order",
				Type:             api.DataTypeStruct,
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			OrderItem: cfg.TypeConfig{
				Name:             "OrderItem",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			OrderItemResult: cfg.TypeConfig{
				Name:             "OrderItemResult",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			OrderState: cfg.TypeConfig{
				Name:             "OrderState",
				Type:             api.DataTypeStruct,
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},
		},
	}
}
